### ISSUE TITLE
-stdin option returns almost immediately after the first few bytes of data.

### ISSUE THREAD

**Issue by enternoescape** [CCExtractor/ccextractor#349] opened 2016-04-04 05:03 UTC
I tried 0.79 pre-compiled Windows binary and compiled the latest git with the same results.

Example command line:
type video.ts | ccextractorwin.exe -stdin -in=ts -out=srt -o video.srt

I am trying to use this as part of a program and it's very desirable to be able to use stdin instead of reading the file from the disk as it's being written.

EDIT: I forgot to include "-o" for the output filename.

**Comment by canihavesomecoffee** [comment] 2016-04-04 05:40
Running the same file regularly works?

**Comment by enternoescape** [comment] 2016-04-04 12:37
Correct.

**Comment by canihavesomecoffee** [comment] 2016-04-04 13:00
I asked if it was running because I wasn't sure you got the output command correct, but I see you've added the -o.

Besides that, if it's running fine when passing it directly instead of through a pipe, it's indeed some windows-related bug.

**Comment by enternoescape** [comment] 2016-04-04 18:47
I figured as much, I was trying to work out what was going on myself, but I wasn't really getting anywhere. All I've really noticed is that the program only gets one successful buffered read of 1083 bytes and then no subsequent reads are successful. It's like stdin is closed.

**Comment by canihavesomecoffee** [comment] 2016-05-22 11:37
I've done some testing, and in my case (depending on the input size) the amount of bytes it's able to read before it stops receiving data varies (from 299 to 95959 bytes). It also varies depending on if you specify an -in, or use -autoprogram (in the latter case it seems to read more).

I can't really find any useful hints or similar issues either online, so I'm afraid that at the moment this one will remain open :cry:

**Comment by cfsmp3** [comment] 2016-05-31 19:36
These seem to be good hints

http://stackoverflow.com/questions/30968377/command-line-tool-to-get-binary-data-as-string-in-windows-like-cat

http://stackoverflow.com/questions/7924365/windows-pipes-in-binary-mode

**Comment by cfsmp3** [comment] 2016-11-04 18:06
This is likely a duplicate of this:
https://github.com/CCExtractor/ccextractor/issues/434

@enternoescape can you check if the problem is fixed for you? (precompiled binaries available on that ticket)

**Comment by enternoescape** [comment] 2016-11-04 20:53
I didn't see any binaries. I downloaded the latest code and compiled it. Unfortunately, the issue described here still exists.

**Comment by cfsmp3** [comment] 2016-11-04 22:47
Can you try this binary?

https://github.com/CCExtractor/ccextractor/files/530373/ccextractorwin.0.83.alpha2-windows.binary.zip

**Comment by enternoescape** [comment] 2016-11-05 00:13
It has the same problems.

**Comment by cfsmp3** [comment] 2016-11-09 18:45
Code-in task created.

**Comment by cfsmp3** [comment] 2016-12-15 00:14
@enternoescape We've released 0.83 today - does this problem still happen to you?

**Comment by enternoescape** [comment] 2016-12-16 02:37
It is still exhibiting the same behavior.

**Closed** 2016-12-24 09:32 UTC
