### ISSUE TITLE
Error data is continuously output

### ISSUE THREAD

**Issue by HaneolLee** [CCExtractor/ccextractor#730] opened 2017-04-05 07:32 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [x] YES - *please specify the last known working version* CCEctractor 0.85
- What platform did you use? [x] Windows - [ ] Linux - [ ] Mac
- What where the used arguments? --gui_mode_reports  -autoprogram  -out=ttxt -nobom -utf8 --norollup -svc 1,2 [+input files]

**Video links**
Recording file
https://drive.google.com/open?id=0BxFzM3fSXVOiOFl1SGRlQnNNNms

An error screen was recorded.
https://drive.google.com/open?id=0BxFzM3fSXVOiRG9yNDFnN1NrSGM

**Additional information**
Ccextractor continues to output dumps of error data
Please check the attached video.

**Comment by cfsmp3** [comment] 2017-04-11 00:12
There's some kind of problem with the input file (a NAL fails to be decoded) and after that CCExtractor is unable to recover. Must be possible since VLC does it though. 

This will need some patience and debugging timing.

GSoC: 5 points.

**Comment by cfsmp3** [comment] 2018-01-11 22:33
Update: Issue still present in 0.86, still valid for GSoC 2018

**Comment by harrynull** [comment] 2018-01-15 11:42
AFAIK, the error logs have nothing to do with NAL failing to decode. NAL failure only causes the debug log (which is usually hided) to be shown (by setting `temp_debug`). The reason ts package having length of 0 is adaptation_field_length + 1 sometimes being the same as  `payload->length`.

**Comment by cfsmp3** [comment] 2018-01-15 15:20
You might be right... can you fix it? :-)

**Comment by MatejMecka** [comment] 2018-10-24 14:46
The file doesn't exist anymore!

It leads to a error 404 page.

No Sample I cannot reproduce :/

**Comment by cfsmp3** [comment] 2018-10-24 14:54
@HaneolLee Do you still have the file? If yes please post a new link and we'll reopen the ticket. 
Closing for now.

**Closed by cfsmp3** 2018-10-24 14:54 UTC
Labels: GCI18
