### ISSUE TITLE
[CEA-708] Missing the last subtitle with "Premature end of file"

### ISSUE THREAD

**Issue by Izaron** [CCExtractor/ccextractor#646] opened 2017-01-14 16:57 UTC
Sometimes we have incomplete ts parts because of cropped .ts files, for example:
`Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 168).`

After work we must flush subtitles in current window:
```
Done, processing time = 85 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
[CEA-708] Window 0 dump:

00:04:49:623 --> 00:34:57:394
-놳떵볒뾡 낥 맼쇋뢦 샺쇶뢣룩 샚믬쟒 
뿫뇢낡 믽뇢쇶 뻊삻뇮 뷍뻮벭 샚웷샚뇢 
뷉솤삸럎 맼쟠삻 쟟듙냭. 
[CEA-708] Dump done
[CEA-708] Window 1 dump:

00:30:22:755 --> 00:34:57:394
낭뢪뾡벭 몸뎻뗥뢰 욯쇽 뒺붺820 뾩뇢벭 
뢶쒡냚뷀듏듙. 
-(뻞쒿) 뷃쎻쟘쇖뷅 뾩랯뫐, 냭뢿뷀듏듙. 
[CEA-708] Dump done
```
^ This subtitles are written to the file
But if we have broken .ts file at the end, then we can't flush last sub because of missing show time, but CEA-608 have last sub. Example:
```
Done, processing time = 12 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
[CEA-708] _dtvcc_decoder_flush: Flushing decoder
[CEA-708] [W-1] hide time updated to 00:09:59:131
[CEA-708] _dtvcc_window_copy_to_screen: W-1
[CEA-708] For window 1: Anchor point -> 0, size 2:32, real position 65:0
[CEA-708] we have top [65] and left [0]
[CEA-708] 2*32 will be copied to the TV.
[CEA-708] Screen show time: -00:00:00:001 -> -00:00:00:001
[CEA-708] Screen hide time: -00:00:00:001 -> 00:09:59:131
[CEA-708] Window 1 dump:

-00:00:00:001 --> 00:09:59:131
Our suspect told Petty
Officer Lynn a co-worker
[CEA-708] Dump done
[CEA-708] _dtvcc_screen_print
[CEA-708] Screen hide time: 00:09:59:131 -> 00:09:59:131
[CEA-708] ccx_dtvcc_writer_output: writing... [D:\USA.p8.svc01.srt][5]
[CEA-708] ccx_dtvcc_write_done: no handling required
[CEA-708] dtvcc_free: cleaning up
```
^ These subtitles have written in CEA-608 file with correct timing, but have not in CEA-708 file.

**Comment by cfsmp3** [comment] 2017-01-20 00:55
GSoC qualification: This issues gives 2 points.

**Comment by AlexeyBelezeko** [comment] 2017-03-03 09:17
@Izaron can you provide me with some samples for the task?

**Comment by Izaron** [comment] 2017-03-03 09:29
@AlexeyBelezeko https://ccextractor.org/public:general:tvsamples "US TV 10 minutes samples" - "ESPN.ts" last sub is missed as far I remembered.

**Comment by Izaron** [comment] 2017-03-05 17:47
Sample:
https://drive.google.com/drive/folders/0B_61ywKPmI0Ta2diT3l0eTlHc2c - USA.ts
Run as `ccextractor <path_to_USA.ts> -svc all`
The first file USA.srt is correct
```
...
222
00:09:54,845 --> 00:09:56,411
     a bogus investigation      
      out of your office.       

223
00:09:56,480 --> 00:09:58,480
         The Lynn case?         

224
00:09:58,548 --> 00:09:59,130
         Our suspect told Petty 
        Officer Lynn a co-worker
```
The second file USA.p8.svc01.srt is incorrect
```
...
222
00:09:56,045 --> 00:09:56,479
     <font color="aaaaaa">a bogus investigation</font>      
      <font color="aaaaaa">out of your office.</font>       

223
00:09:57,513 --> 00:09:58,547
         <font color="aaaaaa">The Lynn case?</font>         
```

**Comment by thetransformerr** [comment] 2018-07-09 10:33
@cfsmp3 

hi all,
I worked on this issue and found that this issue can be solved with modifications in decoder output methods but would like to say that such situation is not a bug , as it only happens in streams that are clipped and packet data is incomplete acc to standard size of ts packet parsing is 188 byte

and error originates from here:

https://github.com/thetransformerr/ccextractor/blob/ae73f147a545003ea58c94925cf14891ad43d8dc/src/lib_ccx/ts_functions.c#L216

from what I see below this line is we are using 188 as hardcoded value for size of remaining data packet as per standard/recommendation defined in ISO 13818:1 , and some of the following functions depend on it , like

https://github.com/thetransformerr/ccextractor/blob/ae73f147a545003ea58c94925cf14891ad43d8dc/src/lib_ccx/ts_functions.c#L240

so here we can use dynamic size if possible , I have no idea abt that , but if that is right approach I can move in that direction.

thanks.

**Comment by T1duS** [comment] 2018-11-07 10:09
So, basically we need to add a parameter like --croppedts which when called replaces all 188 to 168. Am I right?

**Comment by cfsmp3** [comment] 2018-11-07 15:49
No, this has nothing to do with packet size, that's always 188. It's about
the command to display the last subtitle frame not being there (since the
stream is incomplete).

What we need is a way to dump the contents of the 708 decoder once we reach
the end of the stream.

**Comment by siv2r** [comment] 2021-01-15 10:21
Hey all,
I would like to take a shot at this issue :)

**Comment by canihavesomecoffee** [comment] 2021-01-15 10:22
Just go ahead :+1:

**Comment by siv2r** [comment] 2021-01-16 17:00
Just to confirm whether I am moving in the right direction. 
The decoder CEA-708 misses writing (in the output file) the last subtitle information whereas the decoder of CEA-608 writes this information (in the output file) for cropped ts files.

I am able to reproduce this issue for the [USA.srt](https://drive.google.com/file/d/0B_61ywKPmI0TQ2VQRUNpdWFZNVE/view?usp=sharing) file using the command `ccextractor <path_to_USA.ts> -svc all` as mentioned by @Izaron. 

I should possibly look into the following cases:
1. Is this due to some issue with the function [`ccx_dtvcc_write_srt`](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708_output.c#L204) in the [`ccx_decoders_708_ouput.c`](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708_output.c)? (maybe [`ccx_decoder_708.c`](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708.c) extracts the last subtitle information but is not writing to the output file) 
2. The [`ccx_decoder_708.c`](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708.c) is not extracting the last subtitle information. In this case, [`ccx_decoder_708.c`](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708.c) must be compared with [`ccx_decoders_608.c`](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_608.c) (which extracts the last subtitle information) to gain some insights. 

@cfsmp3 @canihavesomecoffee Thoughts on this approach?

**Comment by cfsmp3** [comment] 2021-03-02 17:53
Sorry for the late reply - just found this in a pile of emails.
I'd start by looking at the contents of the decode buffer at the very end
of the program. Does it contain the missing text? (and therefore it's just
that we're not writing it to file)

**Comment by PunitLodha** [comment] 2021-03-19 13:39
@cfsmp3 
I was not sure which decode buffer to look for. At the end of `general_loop()`, I looked at `dec_ctx->dtvcc->decoders[0]`, and it had cc_count = 245, but inside `tv->chars`, everything has sym = 0. There was also a window defined, but rows in it were empty.
So, I am not sure what to make of it, and how to proceed ahead

Also i looked at how 708 subtitles were extracted, and i guess the store_hdcc() is used for storing data into `dec_ctx->cc_data_pkts`. This function is not being called at the end when we get the message:- Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 168). So it might mean that subtitles were not extracted?

**Comment by cfsmp3** [comment] 2021-03-21 20:05
> @cfsmp3
> I was not sure which decode buffer to look for. At the end of `general_loop()`, I looked at `dec_ctx->dtvcc->decoders[0]`, and it had cc_count = 245, but inside `tv->chars`, everything has sym = 0. There was also a window defined, but rows in it were empty.
> So, I am not sure what to make of it, and how to proceed ahead

I wrote this so long ago I don't even remember the specifics. What you can do this set a breakpoint in the code where the 708 data starts being processed. That's in this file: ccx_decoders_common.c, function do_cb, look for case 3: //EIA-708

And well, follow the code to see what happens.

**Comment by PunitLodha** [comment] 2021-03-22 06:22
Tried that, after getting the message:- Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 168),  we return from this line https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_common.c#L103-L106 and never reach case 3

**Comment by cfsmp3** [comment] 2021-03-22 13:17
> Tried that, after getting the message:- Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 168), we return from this line https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_common.c#L103-L106 and never reach case 3
> It says skipping non data, So that could mean data for the final subtitle is not extracted?

This suggests that the sample does not have CEA-708 subtitles but just 608 subtitles. You can find that out by playing the video with VLC and look at the media information or with ffprobe.

If it doesn't have 708 subtitles then the first problem would be on the title of this issue :-) It could be just 608, which would be handled by case 0.

And then the issue is actually the same - we're not processing the buffer at the end of the stream. Which I must say seems strange but it's possible.

**Comment by PunitLodha** [comment] 2021-03-22 13:26
I didn't frame my comment correctly. It does reach case 3, just not after the message. So here is how it goes:-
- In general loop we get more data from the .ts file 
- Then we reach case 3 and after which 708 subtitles are extracted
- This continues until the last subtitle
- Now when we try to get more data from .ts file, we get this message:-  Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 168)
- After this we return from this line https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_common.c#L103-L106 and never reach case 3

**Comment by cfsmp3** [comment] 2021-03-22 20:19
> I didn't frame my comment correctly. It does reach case 3, just not after the message.

Of course, when that message appears there's no more data. 
So you'd need to check if there's anything on the 708 buffer and if yes, manually trigger a buffer flush.

In theory that should be happening already, but set a breakpoint on the function flush_cc_decode and see if it's called or not.

>     * Now when we try to get more data from .ts file, we get this message:-  Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 168)

That's fine, that just means that the stream was abruptly cut. If you added 20 bytes to the end of the file you would get rid of that specific message (since now the file would end with a complete TS block) but wouldn't get any additional data (I think? Feel free to try). In any case this message it's not important.

**Comment by PunitLodha** [comment] 2021-03-23 06:57
> but set a breakpoint on the function flush_cc_decode and see if it's called or not.

flush_cc_decode is called, and that in turn calls, ccx_dtvcc_decoder_flush (i guess this is for 708). Here no decoder window is visible(All windows have `window->visible`==0), so nothing changes

**Comment by cfsmp3** [comment] 2021-03-23 15:25
OK let's close this then as a non-issue then.

**Closed by cfsmp3** 2021-03-23 15:25 UTC
Labels: CEA-708, difficulty: easy, needs-confirmation-of-being-broken

**Comment by PunitLodha** [comment] 2021-04-11 17:42
> flush_cc_decode is called, and that in turn calls, ccx_dtvcc_decoder_flush (i guess this is for 708). Here, https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708.c#L836, no decoder window is visible(All windows have `window->visible`==0), so nothing changes

So I found out what the issue is. None of the windows are visible, but one window is defined, and it has the last subtitle in it. So i changed the condition to check if window is defined or not. But now there's an issue that there is no show time for the subtitle. Hide time is update when flushed, but we are missing the show time. This leads to no subtitles being displayed.
How should we get the show time?
