### ISSUE TITLE
.78 & .79 crash when processing attached bin file

### ISSUE THREAD

**Issue by DHLgh** [CCExtractor/ccextractor#277] opened 2016-02-07 18:37 UTC
This issue began with version .78 and is still present in .79. Thank you!
[ProblemFile.zip](https://github.com/CCExtractor/ccextractor/files/120846/ProblemFile.zip)

**Comment by barun511** [comment] 2016-03-12 19:01
Unable to reproduce, running ccextractor returns the attached file (turned into a .txt to comply with git)
[problemfileresult.txt](https://github.com/CCExtractor/ccextractor/files/170548/problemfileresult.txt)

**Comment by anshul1912** [comment] 2016-03-12 19:13
Already solved by arbitrer, only reproducible on Windows

**Comment by cfsmp3** [comment] 2016-03-12 19:19
But is this solution good? Isn't it the one that checked if the file was
open instead of the reason for which it could be closed?

On Sat, Mar 12, 2016 at 8:13 PM, Anshul Maheshwari <notifications@github.com

**Comment by canihavesomecoffee** [comment] 2016-05-22 09:14
Can be closed once #323 is merged (after bot confirms that PR doesn't introduce new regressions). Tested the PR manually and it solves this issue.

**Closed** 2016-05-22 16:38 UTC
