### ISSUE TITLE
Windows build of 0.88 never works

### ISSUE THREAD

**Issue by ahmedtds** [CCExtractor/ccextractor#1116] opened 2019-10-29 05:51 UTC
It just crashes every time, you probably never tested it on a 32bit system so that's why nobody still noticed it, I'm waiting for months maybe you will notice and fix it but nope

Please fix it, thanks

This is the build I'm talking about: https://github.com/CCExtractor/ccextractor/releases/download/v0.88/ccextractor.0.88-windows.binaries.zip

0.85 works without an issue

OS: Windows 7 32bit

**Comment by MatejMecka** [comment] 2019-10-29 07:56
Hey there! Can you leave us any stacktrace or a way how to reproduce it? We know the environment you are running but can we achieve the crash?

**Comment by ahmedtds** [comment] 2019-11-02 04:35
> 
> 
> Hey there! Can you leave us any stacktrace or a way how to reproduce it? We know the environment you are running but can we achieve the crash?

Hi, just try to use it on 32bit Windows 7 you'll see it will always crash. Open the GUI, drag and drop a mp4 file and Press start and it will crash. Like I said it just never works since 0.88 came out.

**Comment by vikramcs** [comment] 2019-11-07 18:34
configuration.yaml entries and (fill out even if it seems unimportant):

homekit:
port: 51827
ip_address: 192.168.1.116
filter:
include_domains:
- alarm_control_panel
- light
- switch
- fan
- climate
- media_player
- lock
- sensor

Traceback (if applicable):


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit/__init__.py", line 84, in async_setup
    await hass.async_add_executor_job(homekit.setup)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit/__init__.py", line 226, in setup
    port=self._port, persist_file=path)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit/accessories.py", line 194, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyhap/accessory_driver.py", line 195, in __init__
    self.http_server = HAPServer(network_tuple, self)
  File "/usr/local/lib/python3.7/site-packages/pyhap/hap_server.py", line 801, in __init__
    super(HAPServer, self).__init__(addr_port, handler_type)
  File "/usr/local/lib/python3.7/socketserver.py", line 455, in __init__
    self.server_close()
  File "/usr/local/lib/python3.7/site-packages/pyhap/hap_server.py", line 872, in server_close
    for sock in list(self.connections.values()):

**Comment by MatejMecka** [comment] 2019-11-07 18:38
Hey @vikramcs this is not the correct repository you are filling an issue. Since the error appears there file it there :)

Thanks

**Comment by ahmedtds** [comment] 2019-11-20 01:26
any progress?

**Comment by cfsmp3** [comment] 2019-11-30 15:24
@ahmedtds we have a task for this during GCI, hopefully someone will give it a try.

**Comment by flabbet** [comment] 2019-12-06 21:35
[Release.zip](https://github.com/CCExtractor/ccextractor/files/3934088/Release.zip) I succesfully built it, included zip with binary. You can check it out.

**Comment by ahmedtds** [comment] 2019-12-06 22:06
> 
> 
> [Release.zip](https://github.com/CCExtractor/ccextractor/files/3934088/Release.zip) I succesfully built it, included zip with binary. You can check it out.

your zip only has ccextractorgui.exe, it's useless without command line program (ccextractorwin.exe), and ccextractorwin.exe is the one which crashes after pressing start button in gui.

**Comment by flabbet** [comment] 2019-12-07 11:54
> > [Release.zip](https://github.com/CCExtractor/ccextractor/files/3934088/Release.zip) I succesfully built it, included zip with binary. You can check it out.
> 
> your zip only has ccextractorgui.exe, it's useless without command line program (ccextractorwin.exe), and ccextractorwin.exe is the one which crashes after pressing start button in gui.

Edited commend with updated files

**Comment by cfsmp3** [comment] 2019-12-07 19:35
Here's the 4 binaries I manage to build with VS2019. In theory one of the profiles is WinXP compatible, but I don't know. The old XP profiles (v120 and v110) just don't produce any binary due to dependency link errors. Rebuilding tesseract for WinXP compatibility is definitely something I really don't want to do.

Anyway @ahmedtds let us know if this solves the problem (and if yes, which of the binaries work for you).

[CCExtractor_release_binary_test.zip](https://github.com/CCExtractor/ccextractor/files/3935480/CCExtractor_release_binary_test.zip)

**Comment by cfsmp3** [comment] 2019-12-22 04:02
Closing due to user not responding.

**Closed by cfsmp3** 2019-12-22 04:02 UTC
Labels: GCI19

**Comment by ahmedtds** [comment] 2020-03-21 18:56
@cfsmp3 can you re-open this please? sorry for late respond, I had lost the file accidentally before so couldn't test it again. But now I have tested with all the 4 executables you provided and all of them crashes as well.

Command line:
`ccextractorwin.exe  --gui_mode_reports  -out=srt -bom -utf8 --nofontcolor -trim [+input files]`

Result:
```
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: C:\itunes\Yomeddine (1080p HD).m4v
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: Yes]
[Add font color data: No] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]


-----------------------------------------------------------------

Opening file: C:\itunes\Yomeddine (1080p HD).m4v
Detected MP4 box with name: ftyp
Detected MP4 box with name: moov

File seems to be a MP4

Analyzing data with GPAC (MP4 library)
Opening 'C:\itunes\Yomeddine (1080p HD).m4v': 
```

And then crash, same with the files you provided as well.

0.85 works without a problem.

I can upload the sample to google drive and give you a link privately via mail (it's a movie from itunes so don't want to post it publicly)

**Comment by ahmedtds** [comment] 2020-03-21 19:02
Btw, I'm using Windows 7 32-bit OS, if you don't see the bug, maybe install Win7 32-bit to a VM and try to test it on it. I have a feeling this bug may only occur on 32-bit OSes.
