### ISSUE TITLE
Premature end of file.

### ISSUE THREAD

**Issue by Dhrumil2910** [CCExtractor/ccextractor#304] opened 2016-03-09 07:59 UTC
File Link: https://drive.google.com/open?id=0B5-K4mJ0WYBTeEN6ZWFDV2lIbUk
When ccextractor is executed on this file, it is giving result as "Premature end of file". Because of that the appropriate .srt file is not created. 
On running the same on vlc, closed captions are coming flawlessly.

I think, it shouldn't matter whether the video file is cut or not, ccextractor should give the relevant cc.

**Comment by cfsmp3** [comment] 2016-03-09 09:42
Premature end of file doesn't cause CCExtractor not to generate output... maybe the type of subtitles is not supported? What are they?

**Comment by Dhrumil2910** [comment] 2016-03-09 09:52
Standard is EIA-608/708 North America closed captioning

**Comment by abhibansal530** [comment] 2016-03-18 21:42
@canihavesomecoffee Can you please run tests on this??

**Comment by canihavesomecoffee** [comment] 2016-03-18 21:49
@ccx-testerbot runtests master

**Comment by cfsmp3** [comment] 2016-05-27 22:45
The "premature end of file" message is caused by the file ending abruptly (the last TS packet is not complete). That's correct. We've changed the error message so it's more specific.

The failure to extract subtitles is unrelated and caused by CCExtracting selecting a different PID than the one carrying the subtitles. We're looking into this.

**Comment by ykarim** [comment] 2016-11-29 02:40
@cfsmp3 Wasn't this issue resolved in 0373ba5d3aeedf87cd2c58f65aa902ae0fadf174?

**Comment by cfsmp3** [comment] 2016-11-29 02:42
I don't know, was it? :-)

**Comment by grave-w-grave** [comment] 2017-01-07 02:04
It was not! Still gives an empty .srt file. 

```
CCExtractor 0.84, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: Closed Caption EIA.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: Closed Caption EIA.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Creating Closed Caption EIA.srt
Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 1).

Warning: Reference clock has changed abruptly (-590 seconds filepos=1), attempting to synchronize
Last sync PTS value: 53128504
Current PTS value: -9223372036854775808
Note: You can disable this behavior by adding -ignoreptsjumps to the parameters.

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:        00:00:00:000  (0 frames at 29.97fps)

Min PTS:                                -2697393868:36:48:620
(Reference clock was reset at some point, Min PTS is approximated)
Max PTS:                                -2697393868:36:48:620
Length:                          00:00:00:000
Done, processing time = 1 seconds
This is beta software. Report issues to carlos at ccextractor org...
```

**Comment by cfsmp3** [comment] 2017-01-20 00:56
GSoC qualification: This issues gives 3 points.

**Comment by cfsmp3** [comment] 2017-12-08 15:38
Closing - file no longer available. Reopen if needed.

**Closed by cfsmp3** 2017-12-08 15:38 UTC
