### ISSUE TITLE
No captions found (default settings)

### ISSUE THREAD

**Issue by ShraxO1** [CCExtractor/ccextractor#1239] opened 2020-02-28 12:22 UTC
Please prefix your issue with one of the following: [BUG],[QUESTION].
CCExtractor version: {Windows GUI 0.88}

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? {NO}
- What platform did you use? {Window}
- What were the used arguments? `{}`

# Video links

https://drive.google.com/open?id=0B_61ywKPmI0TSlZmUGhKS2tOWHc

# Additional information

Total frames time:	  00:12:56:375  (23268 frames at 29.97fps)

Min PTS:				00:00:00:080
Max PTS:				00:15:30:706
Length:				 00:15:30:626

Done, processing time = 1 seconds

No captions were found in input.
I am getting a 0kb file.
Is this a bug or i am using wrong settings?

**Comment by NilsIrl** [comment] 2020-02-28 15:50
The captions in this file aren't actually captions but are just an image on a video (AFAICT).

**Comment by cfsmp3** [comment] 2020-02-28 16:06
These are burned-in subtitles. You can try with the hardsubs options, it _could_ work.

**Comment by ShraxO1** [comment] 2020-02-28 17:14
I tried that but I am getting an error.
Error: Parameter -hardsubx not understood

**Comment by MatejMecka** [comment] 2020-02-28 18:44
Did you compile with `--enable-hardsubx`?

**Comment by ShraxO1** [comment] 2020-02-28 18:56
C:\Users\Shray Tyagi\Downloads\ccextractor.0.88-windows.binaries\ccextractorwin.exe  --gui_mode_reports  -out=srt -bom -latin1 -hardsubx -subcolor white -conf_thresh 60 [+input files]

This is the command.

**Comment by Cryosim** [comment] 2020-03-12 11:56
Hello. Same issue. Closed captions not found. No captions were found in input.
This captions detect only in VLC as track № 3 EIA 608 (C608)
I try extract with mkvtoolnix or ffmpeg, but doesn't detect subtitle tracks EIA 608

**Comment by MatejMecka** [comment] 2020-03-12 12:39
Can you give us a sample to try and reproduce it? It'll be easier for us to
debug :)

**Comment by ShraxO1** [comment] 2020-03-12 12:48
I have given the video link + command above.

**Comment by Cryosim** [comment] 2020-03-12 12:56
@MatejMecka Sample. https://drive.google.com/open?id=1WrIXlN4l_oVaRJWwoi8Xxp5h7G37IwPs

**Comment by cfsmp3** [comment] 2020-04-12 21:27
@Cryosim Your sample is totally different (a Mastroka file with several subtitle tracks). You should open your open issue.

**Comment by cfsmp3** [comment] 2020-04-12 21:58
I'm closing this because the fundamental error is that @ShraxO1 doesn't have the OCR enabled version of CCExtractor - HOWEVER I will be opening a new ticket with more details of what I'm seeing myself while testing this.

**Closed by cfsmp3** 2020-04-12 21:58 UTC
