### ISSUE TITLE
[BUG] DVB subtitles timing issue

### ISSUE THREAD

**Issue by jakubvojacek** [CCExtractor/ccextractor#1104] opened 2019-09-03 08:35 UTC
CCExtractor version (using the --version parameter preferably) : **0.88** (724d756aa6b90daf83e7a652f956ce29c20ac210)

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [X] I absolutely love CCExtractor, but have not contributed previously.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - we havent noticed that before. It only appers to be happening on some channels, not all.
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What were the used arguments? `ccextractor -in=ts  -ocrlang por -quant 0  -datapid 0x1448  telecine.ts`

**Video links (replace text below with your links)**
https://bit.ly/2kczK9X

**Additional information**
The subtitles are parsed out perfectly, the only issue is that whenever there is silence (nobody speaking), the last subtitle is always shown, until someone starts to speak. You can easily test this in VLC, turn on DVB subs on for example on 0:46, there is a pause in the subtitles (none are showing in VLC). 

In the extracted subtitles, there is no pause, each subtitle is always 1ms after the previous ends - see below:

```
00:00:38.883 --> 00:00:44.987
<font color="#74750b">Por que demoraram tanto?</font>

00:00:44.988 --> 00:00:49.697
<font color="#74750b">Chandler, acaIme-se.</font>
<font color="#74750b">Me deixe preparar minha equipe.</font>
```

Is there a configuration option that we can use to fix this? Or is this an issue in the ccextractor?

Thank you
Jakub

**Comment by vikramcs** [comment] 2019-11-07 18:45
The other issue I'm finding when editing files that have run through OCR is that the outputted .srt file doesn't provide any gaps on screen when there's no talking.

What I mean is this.
I've just been editing a documentary series.

Firstly, no matter when the talking actually first occurs, the first line of dialogue is shown right at the start of the .srt.

Also, when the title music plays and there's no talking, instead of showing no subtitle, it shows whatever the next line of dialogue will be throughout the title sequence and right up until the line is actually spoken.

Another example is that in the last episode I looked at, there was a 1 minute section with no talking, while some wildlife was doing it's thing.

Once again, after the last line of dialogue was spoken and the correct subtitle displayed, my .srt file then displays what will be the next line of dialogue for the entire 1 minute +, until the line is actually spoken.

The outputted .srt doesn't seem to support any gaps between speaking, and always shows the following line of text on screen.
I've been manually editing the .srt in Notepad++, setting the first line to start with wherever the actual dialogue starts. Then also changing the start time of the first line of dialogue after the title sequence, so that this line of text isn't on screen during the entire title sequence, and then I try to manually scroll through and spot where there seem to be any unnaturally long cases of a line of text remaining on screen.

**Comment by NilsIrl** [comment] 2019-12-22 17:54
Investigating

**Comment by NilsIrl** [comment] 2019-12-22 18:40
None of the arguments are relevant to the problem.

**Comment by NilsIrl** [comment] 2019-12-22 18:50
mpv gives the same output as ccextractor. (There aren't any pause between the subtitles)

I couldn't test on vlc as vlc doesn't want to open the file

**Comment by NilsIrl** [comment] 2019-12-22 19:08
There are 2 subtitle stream in the file. Stream 2 seems to correspond with the output given by CCExtractor and has no pauses between the subtitles.

**Comment by NilsIrl** [comment] 2019-12-22 19:08
To me, there is no bug here

**Comment by NilsIrl** [comment] 2019-12-22 19:20
If the timestamps are supposed to be in sync with the video, the timestamps aren't in sync with the ones given by mpv.

The problem is not only that there are gaps between the timestamps but that the timestamps are wrong

**Comment by NilsIrl** [comment] 2019-12-22 19:33
This line seems to be the origin of the problem:

https://github.com/CCExtractor/ccextractor/blob/c1c0627dab772c3626b913ac9113f7a16c2e0773/src/lib_ccx/dvb_subtitle_decoder.c#L1689

**Comment by NilsIrl** [comment] 2019-12-23 15:20
@cfsmp3 is there any possibility this could be a regression?

**Comment by NilsIrl** [comment] 2019-12-23 16:40
May or may not be the function that collects the timings

https://github.com/CCExtractor/ccextractor/blob/c1c0627dab772c3626b913ac9113f7a16c2e0773/src/lib_ccx/ts_functions.c#L741

**Comment by jakubvojacek** [comment] 2019-12-23 18:35
Hello @NilsIrl , thank you for looking into this. 

I tested the file on VLC again, selected the first track (`DVB Subtitles - [Portuguese]`) and it was showing pauses in between subtitles, unlike the generated srt file by ccextractor. I can provide a recorded video of the VLC player if necessary.

Please let me know if you need any further clarification/

Once again, thank you
Jakub

**Comment by NilsIrl** [comment] 2019-12-23 19:01
No, don't worry, as you can see, I have striked-through my comments, I accidentally used ccextractor's output as subtitles for mpv which is why I was confused.

**Comment by cfsmp3** [comment] 2019-12-27 16:31
> @cfsmp3 @jakubvojacek is there any possibility this could be a regression?

Very likely.

**Comment by NilsIrl** [comment] 2020-01-10 20:47
After bisecting I found the commit that made timing *look* sensible for the first time:

016674b0eb4ef09466f9f70575805567fd406bac

This is what it looked like before:

```xml
<subpictures>
<stream>
<!-- ../build/files/telecine.ts -->
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0000.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0001.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0002.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0003.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0004.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0005.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0006.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0007.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0008.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0009.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0010.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0011.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0012.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0013.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0014.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.006" image="../build/files/telecine.d/sub0015.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0016.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0017.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0018.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0019.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0020.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0021.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0022.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0023.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0024.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0025.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0026.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0027.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0028.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0029.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0030.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0031.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.002" image="../build/files/telecine.d/sub0032.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0033.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0034.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.002" image="../build/files/telecine.d/sub0035.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0036.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0037.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0038.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0039.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0040.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0041.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0042.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0043.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0044.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0045.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0046.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0047.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0048.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0049.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0050.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0051.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0052.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0053.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0054.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0055.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0056.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0057.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0058.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0059.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0060.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0061.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0062.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0063.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0064.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0065.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0066.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0067.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0068.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0069.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0070.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0071.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0072.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0073.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0074.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0075.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0076.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0077.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0078.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0079.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0080.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0081.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0082.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0083.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0084.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.002" image="../build/files/telecine.d/sub0085.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0086.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0087.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0088.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0089.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0090.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0091.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0092.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0093.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0094.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0095.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0096.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0097.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0098.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0099.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0100.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0101.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0102.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.005" image="../build/files/telecine.d/sub0103.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.002" image="../build/files/telecine.d/sub0104.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0105.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0106.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0107.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0108.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0109.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0110.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.002" image="../build/files/telecine.d/sub0111.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0112.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0113.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0114.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0115.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0116.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.002" image="../build/files/telecine.d/sub0117.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0118.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0119.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0120.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0121.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0122.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0123.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0124.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0125.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0126.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0127.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0128.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0129.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0130.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0131.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0132.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.003" image="../build/files/telecine.d/sub0133.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0134.png" xoffset="88" yoffset="46">
</spu>
<spu start="0.001" end="0.004" image="../build/files/telecine.d/sub0135.png" xoffset="88" yoffset="46">
</spu>
</stream>
</subpictures>
```

**Comment by NilsIrl** [comment] 2020-01-11 00:13
a5dcf9242d59b30ae78118a96e914d2adbab04a7 is the commit that made all subtitles one next to the other.

**Comment by cfsmp3** [comment] 2020-01-11 00:17
I think that was Anshul's original work on DVB, but that specific issue (as
well was many related to times) were fixed in 2017.
So there must be another commit that reintroduced the problem.

**Comment by NilsIrl** [comment] 2020-01-11 00:18
So it's a double regression?

**Comment by cfsmp3** [comment] 2020-01-11 00:35
I'd call it a regression :-) The first implementation did DVB but
timing was broken (completely).
Then it was fixed, by a GCI winner by the way I think in 2016, and
clearly seems to be broken again.
I haven't looked at the code at all but if you're looking into this
some background:

In DVB subtitles are replaced by subtitles- they don't have a
duration, and there isn't a clear screen command. This means that if
you write something it stays there until something else replaces
it(*). However, that "something else" can be "nothing" (as in empty).
My guess is that we are now filtering that and when there's an empty
string we're not passing it to the encoder. So this is a case of being
to clever optimizing stuff.

(*) Actually the specs mention a timeout of I think 30 seconds, but
let's ignore that case for now.

**Comment by NilsIrl** [comment] 2020-01-11 20:00
Please keep in mind that it isn't the only problem. The other one is that **all** the subtitles are at the wrong "offset".

For the given input file (telecine.ts), it is exactly (at least what my eyes would qualify as such), 6600 millisecond early.

**Comment by cfsmp3** [comment] 2020-01-12 17:33
@NilsIrl compare it with

0.85 (2017-01-23) 
 Fix: DVB timing is finally good.

Let's use 0.85 as the "known good version" for DVB timing reference. 

How are the results on that one?

**Comment by NilsIrl** [comment] 2020-01-12 20:24
0.85 doesn't compile on my computer :smile:

**Comment by NilsIrl** [comment] 2020-01-12 20:24
It doesn't work with cmake or the linux build script

**Comment by NilsIrl** [comment] 2020-01-12 20:47
0.85 doesn't look good to me

**Comment by cfsmp3** [comment] 2020-01-12 20:55
Try a different input file. Maybe that telecine.ts is not great.

https://drive.google.com/drive/folders/0B_61ywKPmI0TUUk5LXJPeG1feFE

I remember I used EastEnders to test and the sync for absolutely perfect.

Remember that you need to compare with the output of the subtitles as
displayed for example with VLC, *not* the audio. The DVB subtitles
might be off-sync with the audio and that's not our problem.

**Comment by NilsIrl** [comment] 2020-01-12 21:11
The results with EastEnders are **perfect** on master.

So the problem is specific to telecine.ts

**Comment by cfsmp3** [comment] 2020-01-12 21:18
Play telecine.is in VLC as well, and enable DVB subtitles. Do they look as
bad as in CCExtractor, or are they in sync? If VLC and CCExtractor do the
same thing I'd say it's safe to say the problem is with that file.

If VLC plays it correctly and we don't, then we have a job to do :-)

**Comment by NilsIrl** [comment] 2020-01-12 21:33
What I do to debug is:

1. generate subtitles with ccextractor
2. Play 1 mpv instance with the subtitles from ccextractor and 1 instance with the subtitles directly from the file.
3. I have a command that makes sure the 2 instances are in sync.

End result:

* The results with east enders on master are in sync.
* The results with telecine.ts are too early and stay up until the next subtitle compaired with the other instance.

**Comment by cfsmp3** [comment] 2020-01-12 21:43
OK but what about the output of mpv relative to audio? Is it in sync, or a
disaster?

If there isn't any player that can play that file correctly, we can forget
about that file, even if the output is different to CCExtractor's (because
we don't know which one is correct). However if mpv plays it correctly
(subtitles and audio are in sync) then we have a problem.

**Comment by NilsIrl** [comment] 2020-01-12 21:45
Yeah MPV (like VLC I assume) gives subtitles that are in sync with the audio (for east enders + telecine).

So the problem is with ccextractor in this specific case.

**Comment by cfsmp3** [comment] 2020-01-12 23:06
Can you fix it? :-)

**Comment by NilsIrl** [comment] 2020-01-13 15:27
> Can you fix it? :-)

I wish. It doesn't look straightforward at all.

**Comment by NilsIrl** [comment] 2020-01-18 19:44
Is there a tool I can use so that I can visualise the difference in program flow between two runs (in this case, compare eastenders and telecine)?

**Comment by NilsIrl** [comment] 2020-01-19 21:50
For those who want to analyze the flow here is the callgrind output for the command:

```bash
TESSDATA_PREFIX=/nix/store/wipcqqi4chy9armmgl9749934sfqzas8-tesseract-4.1.0/share/ valgrind --tool=callgrind ./ccextractor files/01-BBC1.EastEnders.ts
```

and

```bash
TESSDATA_PREFIX=/nix/store/wipcqqi4chy9armmgl9749934sfqzas8-tesseract-4.1.0/share/ valgrind --tool=callgrind ./ccextractor files/telecine.ts
```
[callgrind.zip](https://github.com/CCExtractor/ccextractor/files/4083669/callgrind.zip)

**Comment by wojtekw** [comment] 2020-02-03 20:20
I have similiar problem with ts file.Trying output to spupng but always start of the subtitles is:
<spu start="0.000" end="4.239" 

The very weird for me is that ccx shows in output:
Min PTS:				00:00:38:220
Max PTS:				01:53:39:940


So why the first subtitle is 00:00:00 not 00:00:38 ?


Can anyone help? Lost few days for this issue :(

**Comment by NilsIrl** [comment] 2020-02-03 20:57
> I have similiar problem with ts file.Trying output to spupng but always start of the subtitles is:
> <spu start="0.000" end="4.239"
> 
> The very weird for me is that ccx shows in output:
> Min PTS: 00:00:38:220
> Max PTS: 01:53:39:940
> 
> So why the first subtitle is 00:00:00 not 00:00:38 ?
> 
> Can anyone help? Lost few days for this issue :(

Could you make the `.ts` file accessible? That would help a lot.

**Comment by wojtekw** [comment] 2020-02-03 21:00
Unfortunately can't upload this file anywhere. It's movie from one of the majors.

**Comment by cfsmp3** [comment] 2020-02-03 21:13
We can't help without access to the file.

You can just share a link with us privately by email - of course we deal
with this kind of content all the time.

If that's not an option we really can't help you.

**Comment by wojtekw** [comment] 2020-02-04 07:36
@cfsmp3 I understand but really can't share this movie.
First what I see in this file is that it can't play in VLC but plays in QuickTime

Is that normal when Min PTS:	00:00:38:220 and first line of subtitles is  <spu start="0.000" end="4.239" ?
I expected <spu start="0.000" end="38.220...

**Comment by wojtekw** [comment] 2020-02-16 14:44
Still have this problem, I see that CCX uses FTS timing instead PTS and I can't find which param can change it. 
-gt doesn't work

**Comment by wojtekw** [comment] 2020-02-17 13:46
@NilsIrl Can You help without TS file ? I'm afraid that there is some parameter that can fix this problem.

**Comment by NilsIrl** [comment] 2020-02-17 14:16
> @NilsIrl Can You help without TS file ? I'm afraid that there is some parameter that can fix this problem.

As far as I'm aware, this is a bug and there aren't any ways to fix it apart from actually fixing it.

I'd love to fix it unfortunately I've only worked on the encoders (and this involves decoders) and I'm really lost as to what could fix the problem.

**Comment by cfsmp3** [comment] 2020-02-17 17:17
> @NilsIrl Can You help without TS file ? I'm afraid that there is some parameter that can fix this problem.

If you can't trust us with your file then there's nothing we can do for you I'm afraid. 
Well, unless you actually sponsor the research and then we can spend time trying to blindly solve your problem.
But being blunt, we're not going to do it on our own free time. Sorry.

**Closed** 2020-03-30 17:05 UTC
Labels: difficulty: hard
