### ISSUE TITLE
MXF CEA-608/708

### ISSUE THREAD

**Issue by simonlr** [CCExtractor/ccextractor#207] opened 2015-08-05 15:07 UTC
Unable to pull any information from this MXF. Sorry for the huge post. Here's `mediainfo` CC bit for the file:

General
Complete name                            : C-YKN-SD-RC-V4.mxf
Format                                   : MXF
Commercial name                          : XDCAM HD422
Format version                           : 1.2
Format profile                           : OP-1a
Format settings                          : Closed / Complete
File size                                : 393 MiB
Duration                                 : 59s 393ms
Overall bit rate                         : 55.5 Mbps
Encoded date                             : 2015-07-31 21:20:56.000
Writing application                      : AVID TRMG 3.01

Text #1
ID                                       : 7-CC1
Format                                   : EIA-608
Muxing mode                              : Ancillary data / CDP
Duration                                 : 59s 393ms
Bit rate mode                            : Constant
Frame rate                               : 29.970 fps
Stream size                              : 0.00 Byte (0%)
Language                                 : English

Text #2
ID                                       : 7-1
Format                                   : EIA-708
Muxing mode                              : Ancillary data / CDP
Duration                                 : 59s 393ms
Bit rate mode                            : Constant
Frame rate                               : 29.970 fps
Stream size                              : 0.00 Byte (0%)
Language                                 : English

and CCExtractor output

CCExtractor 0.77, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: C-YKN-SD-RC-V4.mxf
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]

[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: (null)] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
Teletext page: [Autodetect]
Start credits text: [None]

^M-----------------------------------------------------------------
^MOpening file: C-YKN-SD-RC-V4.mxf
^MFile seems to be an elementary stream, enabling ES mode
^MAnalyzing data in general mode
Creating C-YKN-SD-RC-V4.srt

New video information found
[1920 * 1080] [AR: 03 - 16:9] [FR: 04 - 29.97] [progressive: no]

Unexpected startcode: E3
^M  0%  |  00:00
Skip forward to the next Sequence or GOP start.

Skip forward to the next Sequence or GOP start.

Unexpected startcode: E3
^M  1%  |  00:00
Skip forward to the next Sequence or GOP start.

Please let me know if the sample file is needed, it's ~500MB.

**Comment by wforums** [comment] 2015-08-06 19:59
There is no official support for MXF at this point, and as such, it's logical that there's no captions extracted from them ;)

**Comment by cfsmp3** [comment] 2016-05-28 00:46
Closing this for now since it's not a bug but a feature request. It will be done if/when someone sponsors development (or sends us a patch).

**Closed by cfsmp3** 2016-05-28 00:46 UTC

**Comment by discoronin** [comment] 2017-06-13 15:27
Considering that this is a feature request... I have a client requesting it.  If we were to sponsor it... how much and how long make available?  I have a source sample MXF and a SMPTE-TT file that is representative of the desired outcome.  My client currently does this in a multi-step, on-prem, and time intensive manner.  If we can make this a feature of our cloud based workflow, it could be worth something to them.

Cheers,

John
