### ISSUE TITLE
Major memory leak on Manjaro Linux (kernel 5.6).

### ISSUE THREAD

**Issue by artivision** [CCExtractor/ccextractor#1250] opened 2020-04-05 22:42 UTC
Good day i try to **ocr** a hardsub **mp4** and after 100sec my memory is full. This is as far as i can get.

https://ibb.co/1X5GT8t

**Comment by NilsIrl** [comment] 2020-04-06 08:44
> a hardsub **mp4**

could you provide the file?

**Comment by artivision** [comment] 2020-04-06 17:39
> > a hardsub **mp4**
> 
> could you provide the file?

Nope don't have the rights. But its an SD 250MB mp4 file. Also there is no documentation as of how to change **"OCR Mode"** and **"OCR Confidence Threshold"** for better results.

**Comment by artivision** [comment] 2020-04-06 22:37
Officially memory leak for all media, OCR dead. Another mistake also when the created .srt contains one line of wrong subs and bellow it the same line of correct ones with the same time stamp, so very great.

**Comment by cfsmp3** [comment] 2020-04-07 04:27
Closing because there's no sample.

**Comment by NilsIrl** [comment] 2020-04-07 12:40
> Nope don't have the rights.

We can't do anything without the file. As mentioned by @cfsmp3 . However you can share the samples privately by emailing https://ccextractor.org/public:general:support#email.

**Comment by artivision** [comment] 2020-04-07 20:48
> > Nope don't have the rights.
> 
> We can't do anything without the file. As mentioned by @cfsmp3 . However you can share the samples privately by emailing https://ccextractor.org/public:general:support#email. In which case, we _may_ be able to help.

Good day. As i said before it happens on all mp4 with Greek hardsubs. Its not just one so there is no need for sample, also i cannot send a big email like that. You can download similar mp4 yourselves. Please don't close this.

**Comment by cfsmp3** [comment] 2020-04-07 20:52
> Good day. As i said before it happens on all mp4 with Greek hardsubs. 

Then provide one.
Please don't expect to find a file somewhere to troubleshoot a problem that you are having. That's not reasonable.

> You can download similar mp4 yourselves. 

Would you like it we told you that you can also fix the problem yourself since CCExtractor is open source?

**Comment by artivision** [comment] 2020-04-09 19:07
> > Good day. As i said before it happens on all mp4 with Greek hardsubs.
> 
> Then provide one.
> Please don't expect us to find a file somewhere to troubleshoot a problem that you are having. That's not reasonable.
> 
> > You can download similar mp4 yourselves.
> 
> Would you like it we told you that you can also fix the problem yourself since CCExtractor is open source?

OK then, how do i send the sample? Is there a need to fill a request to participate in the team?

**Comment by NilsIrl** [comment] 2020-04-09 19:23
> how do i send the sample?

Just upload to a file sharing service (e.g. firefox send, dropbox or google drive) and then send an email with a link to the file at the address available here https://ccextractor.org/public:general:support#email. Alternatively, if you can share the file publically just post a link here.

But if it happens on all mp4 with Greek hardsubs then you can just find 1 and link it to us.

**Comment by artivision** [comment] 2020-04-09 20:16
> > how do i send the sample?
> 
> Just upload to a file sharing service (e.g. firefox send, dropbox or google drive) and then send an email with a link to the file at the address available here https://ccextractor.org/public:general:support#email. Alternatively, if you can share the file publically just post a link here.
> 
> But if it happens on all mp4 with Greek hardsubs then you can just find a link to such file and post it here.

Random link:

tainio-mania.co/load/seir/roswell_new_mexico_2019/21-1-0-20259
Can be downloaded from Chrome's Network/Media function.

Also i solved the problem for now by compressing videos at 320p fast decode. Then the OCR finishes just before my memory gets to 90% on just 2 minutes.

There is another problem tho. How do i set **Confidence threshold** and **Similarity threshold** from command line?

**Comment by NilsIrl** [comment] 2020-04-09 20:22
> Random link:
> 
> tainio-mania.co/load/seir/roswell_new_mexico_2019/21-1-0-20259
> Can be downloaded from Chrome's Network/Media function.

Unfortunately, it turns out I can't read greek. I have no idea where I am supposed to download the file.

**Comment by artivision** [comment] 2020-04-09 20:56
> > Random link:
> > tainio-mania.co/load/seir/roswell_new_mexico_2019/21-1-0-20259
> > Can be downloaded from Chrome's Network/Media function.
> 
> Unfortunately, it turns out I can't read greek. I have no idea where I am supposed to download the file.

No need, inside **Player 2 (HTML 5)** just press **Season 2** and then **Episode 1**, will start play.
Then **right click on Chrome/Chromium->Control**, when the **inspection page** shows up you choose **Network** and then **Media**. That way you can discover videos on many webpages. Then **right click above the newfound** and **open in new tab**, will start download. You can also finish with **copy link address** instead and give it to another downloader.

**Comment by artivision** [comment] 2020-04-16 19:05
This page works for download better: https://oipeirates.tv/roswell-new-mexico-2019/tainies-online

**Comment by NilsIrl** [comment] 2020-04-16 20:31
> This page works for download better: https://oipeirates.tv/roswell-new-mexico-2019/tainies-online

I've managed do download the other one (was a real pain, but managed to do it nonetheless). So this can be reopened.

**Comment by cfsmp3** [comment] 2023-03-22 04:56
That video link now points to malware. I'm closing this. Some memory leaks were fixed today.
@artivision feel free to reopen if you can reproduce and can produce a sample - thanks.

@NilsIrl if you still have that one around please check it out with master, you never know :-)

**Closed by cfsmp3** 2023-03-22 04:56 UTC
