### ISSUE TITLE
Ripping captions from WTV files ignores all time stamps and commercials

### ISSUE THREAD

**Issue by Silver-Streak** [CCExtractor/ccextractor#452] opened 2016-11-30 02:24 UTC
I have a HTPC I built running Windows 8Windows Media Center. I use MCEBuddy to clean up my recorded WTV files, ripping captions to SRT for my wife, who is deaf and wants to be able to watch the videos throughout the house, and creating edl (I store for later to try and tweak appropriately). 

I noticed that all of a sudden all of my subtitles are WAY out of sync. Like, minutes. Doing some digging, it happened in every file I've ripped CC from since I upgrade MCEBuddy. Digging into that, I saw they updated their version of CC extractor. The previous version of MCEBuddy I had installed (2.3.5) had CCExtractor 0.66,, where as the newer version of MCEBuddy had CCExtractor 0.81.

Looking at output files, it looks like what is happening is that the newly output captioned file act like the show starts at 0:00:00, which is not true, due to commercial/channel logos.  Older captured files (from 0.66, I believe) include the commercials themselves, and seem to be fully in sync. The new files don't appear to have captions at all for the commercials that have them, and timestamps are off by minutes in some cases. 

I've eliminated MCEBuddy from the equation, and have been able to reproduce this behavior on a separate machine with 0.81 vs 0.66. I've attached what each version spits out. Any insight into what I'm doing wrong, or what could have changed, is greatly appreciated.

Created previously
[062116 Arrow_S03E18 - Copysrt.txt](https://github.com/CCExtractor/ccextractor/files/620795/062116.Arrow_S03E18.-.Copysrt.txt)

Created and recreated yesterday
[112816 The Flash (2014)_S03E05 - Copysrt.txt](https://github.com/CCExtractor/ccextractor/files/620796/112816.The.Flash.2014._S03E05.-.Copysrt.txt)

For reference, the first line in the video file this is ripped from doesn't start until 1 minute, 41 seconds.

**Comment by cfsmp3** [comment] 2016-11-30 02:31
Sounds like you are not using the subtitle file on the same video file it
was extracted from? The subtitles are in sync with the source file, but if
you remove clips from that file and generate a new one with missing parts
of course the subtitles are going to be totally off sync.

**Comment by Silver-Streak** [comment] 2016-11-30 02:37
To clarify, these files are being used with the exact same files they're ripped from. Previously, I had been automatically converting these files to MKV and leaving the subtitles external files. To provide additional clarity, these are being recorded via ATSC over the air broadcasts.

Unfortunately, I no longer have the source WTV for the Arrow episode, so I cannot show a 1:1 comparison, as I can no longer get any newly extracted captions to extract with correct timings.

**Comment by Silver-Streak** [comment] 2016-11-30 02:45
Here's a better example. I just reconverted one of the few WTV files I have kept that were good (as I do not reconvert Legends of Tomorrow episodes yet, as I haven't set up the rules within MCEbuddy).

Here is the original caption file. 
  Last line of text with time stamp: 
"1082
01:01:26,951 --> 01:01:34,289
              <i> ♪ ♪</i>    "
[Original LOT_S02E01srt.txt](https://github.com/CCExtractor/ccextractor/files/620826/Original.LOT_S02E01srt.txt)

Here's what 0.81 spat out with clean settings, from the exact same video file:
  Last string and time stamp:
 "
1082
00:56:05,230 --> 00:56:12,568
              <i> ¶ ¶</i>              "
[Just created LOT_S02E01srt.txt](https://github.com/CCExtractor/ccextractor/files/620828/Just.created.LOT_S02E01srt.txt)

**Comment by cfsmp3** [comment] 2016-11-30 02:47
We'd need the source video files. Best thing you can do is upload them to
Google Drive or Dropbox or any other place from which we can download
directly (we won't download from a place in which we need to create an
account or which offer bad speeds unless we pay) and we'll try to figure it
out.

**Comment by Silver-Streak** [comment] 2016-11-30 02:49
So...I could do that, but the source video files are 4 gb each due to being 1080p recorded via HD OTA broadcast. I have the bandwidth to do it if you guys want?

**Comment by cfsmp3** [comment] 2016-11-30 03:03
Yes, we're used to dealing with mammoth files.

**Comment by Silver-Streak** [comment] 2016-11-30 03:06
You got it. Uploading now, will post link tonight or tomorrow once it's done. Thanks for your time and assistance.

**Comment by Silver-Streak** [comment] 2016-11-30 05:05
@cfsmp3  Here you go: https://drive.google.com/open?id=0B-7WslMx37HXV0NyYVF1QndxOWM

**Comment by Silver-Streak** [comment] 2016-12-04 22:20
Sorry if this outside of etiquette, just wanting to check if there's any other info or files I can provide to help on this.

**Comment by cfsmp3** [comment] 2016-12-15 00:53
Problem confirmed in 0.83, we'll look into this.

**Comment by Silver-Streak** [comment] 2016-12-15 00:55
@cfsmp3 Thanks a ton. I'll go ahead and remove the test file for now. Let me know if you need any other clips or if I can assist with testing anything.

**Comment by cfsmp3** [comment] 2016-12-15 01:15
Wait wait please don't remove the file, otherwise other developers can't
work on it.

**Comment by Silver-Streak** [comment] 2016-12-15 02:34
@cfsmp3 Sure thing. Reposting link as I deleted the original comment: https://drive.google.com/open?id=0B-7WslMx37HXV0NyYVF1QndxOWM

**Comment by cfsmp3** [comment] 2017-01-11 01:13
Fixed in current master.

**Closed by cfsmp3** 2017-01-11 01:13 UTC

**Comment by Silver-Streak** [comment] 2017-01-11 01:41
Unfortunately I'm terrible at compiling. How long would I need to wait
until a binary with this master is made available?

**Comment by cfsmp3** [comment] 2017-01-11 01:46
For Windows?

**Comment by Silver-Streak** [comment] 2017-01-11 02:15
Correct.

**Comment by cfsmp3** [comment] 2017-01-11 02:25
Try this one. Not 100% sure all dependencies are there - let us know if it works OK for you.

[ccextractor.0.85-full-RC1.zip](https://github.com/CCExtractor/ccextractor/files/697887/ccextractor.0.85-full-RC1.zip)

**Comment by Silver-Streak** [comment] 2017-01-11 03:45
That's fantastic. I can confirm it works (both in the capacity of
dependencies, and in captions). The video that would no longer produce
proper captions now produces proper captions. As soon as the final release
is out I'll bug the MCEBuddy folks to let them know. In the interim I'll
manually replace it's install path.

Thank you and everyone else so much on this. My wife will be estatic.

**Comment by Silver-Streak** [comment] 2017-01-11 05:36
Hey Carlos,

So...bad news. Sorry to bother you with this.

The test file I provided definitely works now....other files I've thrown at
it are better, but still around 10ish seconds out of sync. I've tested with
3 other video files now and it seems to be the same deal.

Should I upload another test file that is not working?

-Silver

**Comment by cfsmp3** [comment] 2017-01-11 14:08
Sure, send us samples and we'll analyze them... goal is 100% reliability.

**Comment by Silver-Streak** [comment] 2017-01-12 00:28
Thanks Carlos. Here's another test file:
https://drive.google.com/open?id=0B-7WslMx37HXZ3NRY3YtWTJWTEk

A good example issue: In this video, at 40:06 and ending at 40:07, the line
"Barry it doesn't matter what you've done" is said. In the SRT that the
compiled version you gave me spits out, this appears at 00:39:57,229 -->
00:39:58,562

**Comment by saurabhshri** [comment] 2017-01-12 08:24
_Looks like Barry messed up with CEExtractor's timeline too_.

**Comment by brooss** [comment] 2017-01-12 08:55
> The test file I provided definitely works now....other files I've thrown at it are better, but still around 10ish seconds out of sync. I've tested with 3 other video files now and it seems to be the same deal.

I'm not quite clear on what you're reporting here. Is this a new bug (it worked correctly on an older version but is wrong in the newest version)? 

A quick test shows the same output with an old 0.70 build and the latest Git for me with the new test file you uploaded.

**Comment by Silver-Streak** [comment] 2017-01-13 00:18
So, the original test file now works fine with 0.85 RC1. The new test file,
ltest.wtv, does not. As mentioned in the above post, this is the scenario
I'm seeing.


   - Audio in ltest.wtv: at 00:40:06 The line "Barry it doesn't matter what
   you've done" is heard.
   - Playing embedded captions from the recording itself in Windows Media
   Center: Caption and audio are synced to the above time.
   - Use 0.85 RC1 to extract:
      1. In command prompt, navigate to location of ccextractorwinfull.exe
      (from 0.85 RC1)
      2. Run the command "ccextractorwinfull.exe ltest.wtv -o ltest.srt"
      3. Open the finished .srt.
      4. The line "Barry it doesn't matter what you've done" appears in the
      .srt at 00:39:57,229 --> 00:39:58,562
      5. When playing in Windows Media Player Classic with the .srt file
      loaded, all of the captions are out of sync with the audio. The subtitle
      srt text is ahead of the audio by ~10 seconds.

As a precaution, I also uploaded the output .srt here:
https://drive.google.com/open?id=0B-7WslMx37HXcTAzVk9tbkQ2bU0

Also, here is the output of the command line after running the above
command. One thing to notice, the source .wtv has a length of 62:58,
however the detected length in this output is 62:49:

D:\Temp\ccextractor>ccextractorwinfull ltest.wtv -o ltest.srt
CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ltest.wtv
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: ltest.wtv
File seems to be a WTV, enabling WTV mode
Analyzing data in general mode
Creating ltest.srt
100%  |  62:49
Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:        00:00:00:000  (0 frames at 29.97fps)

Min PTS:                                00:00:11:067
Max PTS:                                01:03:00:633
Length:                          01:02:49:566
Done, processing time = 2 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues

**Comment by brooss** [comment] 2017-01-13 12:33
> That said, is it possible this is related to this: #641
No, I don't think so. WTV files never use 708 encoding AFAIK.

Can you try with the -wtvmpeg2 flag on some more of your recordings?
`ccextractorwinfull -wtvmpeg2 ltest.wtv -o ltest.srt`

Some WTV recordings contain two sets of captions, one in a separate MSTV captions stream (default for ccextrator to use) and one in the mpeg2 video. This flag will make ccextractor use the alternative captions from the video stream.

In the sample you provided the -wtvmpeg2 flag seems to give accurate timings, possibly the timings in MSTV stream are simply wrong in the file (for some reason).

**Comment by Silver-Streak** [comment] 2017-01-14 17:09
@brooss Well that is awesome, this works on the test file. Going to test it on some of the others I knew weren't working.

Any ideas on why this would impact only since version updates last year? Did older versions always use this flag? 

Assuming this works on the other files, I can always update MCEBuddy's CCextractor config to accomodate.

I'll post an update once I've tested with at least 2 other files that I know were bad.

**Comment by Silver-Streak** [comment] 2017-01-14 17:19
Okay, ran through an episode of 3 different shows. Without -wtvmpeg2 flag, they all have timings off by ~10 seconds. With the flag, everything is pretty much spot on.

I'll definitely update my config files to include this. 

So this gives me a few questions: 

- Is this something that should still be considered an issue? 
- Should/could ccextractor autodetect this?
- why would it detect the normal channel fine, but just output 10 seconds off?
- 

(Regardless, thank you all for your help)

**Comment by brooss** [comment] 2017-01-19 12:48
Not sure I'm the best person to answer this, but I'll try.

> Is this something that should still be considered an issue?

Best guess, this is probably a case of your WTV files having incorrect times on the MSTV captions (for some unknown reason) in the recordings. But it is possible this is a ccextractor bug still. We are dealing with a proprietary, undocumented format here so it's possible we are parsing something wrong that's causing the offset.

> Should/could ccextractor autodetect this?

It would be possible to autodetect the presence of MPEG2 captions in WTV files I think. If I remember correctly, when I was implementing the WTV functionality, the MPEG2 captions were often incomplete or incorrect though, so I'm not sure it's desirable. The best case would be for somebody to study carefully how the Microsoft players detect and select which stream to use in which circumstances over a large selection of different WTV recordings from different regions and MCE versions/hardware. That's probably a quite large undertaking though.

> why would it detect the normal channel fine, but just output 10 seconds off?

Really difficult to say. At this point I'm assuming it's some bug at record time.

**Comment by Silver-Streak** [comment] 2017-01-22 00:29
@brooss Thank you for the input. I still can't figure out what would have changed on the recordings in that time frame. 

I also found out that there doesn't seem to be a way to pass through commands to CCExtractor from MCEbuddy, which makes this harder. I've posted on their forums and will see if any options come up.

Thank you all for your help.

**Comment by Silver-Streak** [comment] 2017-01-28 18:44
Just going to post this here incase anyone else runs into the same issue I did. Here's how I solved adding this command in MCEbuddy. This will need to be added to your profile's section in profile.conf

CustomCommandPath="C:\Program Files\MCEBuddy2x\ccextractor\ccextractorwin.exe"
CustomCommandParameters= -wtvmpeg2 "%sourcefile%" -o "%destinationpath%\%showname%_S%season%##E%episode%##.srt"
CustomCommandHangPeriod=0
CustomCommandCritical=true
CustomCommandUISession=False
CustomCommandShowWindow=False
