### ISSUE TITLE
Random failures with buffered input on stdin in certain files.

### ISSUE THREAD

**Issue by mackworth** [CCExtractor/ccextractor#436] opened 2016-10-12 01:57 UTC
The symptom is `Error: Syntax problem: Final 0xFF marker missing.` Same video file, same command.  Fails with the -bi; otherwise it works fine.

Here's a sample file.
https://dl.dropboxusercontent.com/u/21507587/RobotChicken-RandomFailuresBI.mpg

Here's a bad pass:
[RobotChickenBad2.txt](https://github.com/CCExtractor/ccextractor/files/523349/RobotChickenBad2.txt)

and here's a good pass:
[RobotChickenGood.txt](https://github.com/CCExtractor/ccextractor/files/520802/RobotChickenGood.txt)

When I run it 20 times, I get this:

```
> MacBook-Pro:mac hugh$ for i in $(seq 1 1 20); do
> cat "$f" | $ccextractor -bi - -o junk3.srt > "junkNew$i.log"
> if [ $? -eq 0 ]
> then
>   echo "OK   - $f"
> else
>   echo "Fail - $f"
> fi
> done
OK   - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
OK   - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
OK   - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
OK   - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg
Error: Syntax problem: Final 0xFF marker missing.
Fail - /Volumes/External/TivoShows/Robot Chicken- Celebrity Rocket (Decrypted TiVo Show)-2.mpg

```

When I turn on `-debug and -vides` the log looks like this
[RobotChickenBad.txt](https://github.com/CCExtractor/ccextractor/files/523320/RobotChickenBad.txt)

The difference is here (3912 lines in). In multiple passes, I've seen the prev/curr numbers becomes 4/15, 4/9 and 4/2 as well.

``` diff
 IdrPicFlag=               0
 pic_order_cnt_lsb=       15
 END   NAL unit type: 1 length 2443 ref_idc: 3 - Buffered captions after: 0
-TS continuity counter not incremented prev/curr 4/15
 PES header length: 19 (19 verified)  Data length: 0
 PTS: 02:09:48:511 (700966052)  FTS: 00:00:02:252 
 process_avc: zeropad 1
 BEGIN NAL unit type: 9 length 1 ref_idc: 0 - Buffered captions before: 0
 END   NAL unit type: 9 length 1 ref_idc: 0 - Buffered captions after: 0
 process_avc: zeropad 1
-BEGIN NAL unit type: 6 length 16318 ref_idc: 0 - Buffered captions before: 0
+BEGIN NAL unit type: 6 length 92 ref_idc: 0 - Buffered captions before: 0
 Payload type: 0 size: 1 - 
 Payload type: 1 size: 1 - 
 Payload type: 4 size: 71 - 
 Caption block in ANSI/SCTE 128...ATSC1_data()...
 cc_data (finally)!
-Error: Syntax problem: Final 0xFF marker missing.
+Payload type: 4 size: 10 - 
+Caption block in ANSI/SCTE 128...
+END   NAL unit type: 6 length 92 ref_idc: 0 - Buffered captions after: 1
+process_avc: zeropad 1
+BEGIN NAL unit type: 1 length 1681 ref_idc: 0 - Buffered captions before: 1
+
+SLICE HEADER
+first_mb_in_slice=        0 (0)
+slice_type=               1
+pic_parameter_set_id=     0 (0)
+frame_num=                7
+field_pic_flag=           1
+bottom_field_flag=        0
+IdrPicFlag=               0
+pic_order_cnt_lsb=       12
+END   NAL unit type: 1 length 1681 ref_idc: 0 - Buffered captions after: 0
+PES header length: 19 (19 verified)  Data length: 0
+PTS: 02:09:48:528 (700967554)  FTS: 00:00:02:202 
+process_avc: zeropad 1
+BEGIN NAL unit type: 9 length 1 ref_idc: 0 - Buffered captions before: 0
+END   NAL unit type: 9 length 1 ref_idc: 0 - Buffered captions after: 0
+process_avc: zeropad 1
+BEGIN NAL unit type: 6 length 19 ref_idc: 0 - Buffered captions before: 0
+Payload type: 0 size: 1 - 
+Payload type: 1 size: 1 - 
+Payload type: 4 size: 10 - 
+Caption block in ANSI/SCTE 128...
+END   NAL unit type: 6 length 19 ref_idc: 0 - Buffered captions after: 0
+process_avc: zeropad 1
```

**Comment by mackworth** [comment] 2016-10-12 15:32
Let me add a question, now that you fixed the other issue, I could just drop the bufferedInput flag and avoid this issue.  What is the reason for the flag? Is there better performance with it? (Just FYI, I'm the developer for cTiVo, which downloads shows from the TiVo to your Mac, coordinating tivodecode, ffmpeg, mencoder, handbrake, ccextractor, and comskip. So I've got a steady stream of these files coming over, and construct a pipeline for each one.)

And thank you for an excellent program!

**Comment by cfsmp3** [comment] 2016-10-12 22:09
This one is going to be a tough one I think. For starters I can't reproduce:

OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg
OK   - RobotChicken-RandomFailuresBI.mpg

About your question, you probably don't want to buffer in Mac. Best thing you can do is just run CCExtractor with and without the flag and compare execution time. But I remember that in linux the internal buffer actually made things slower while in Windows it seemed to help which is why default behavior is different in each platform.

On the other hand, even if you don't care about the buffer anymore we shouldn't have a bug running around :-) You never know when it's going to bite.

**Comment by mackworth** [comment] 2016-10-13 16:14
so, and I have the opposite problem!  I can run it, somewhat reliably get it to fail, load it in the debugger stop at the error point, and look around.  I just have no idea what it all means.  Let me play with it some and see if I can identify the place where good and bad runs diverge and see what I can find. Looks to me like `TS continuity counter not incremented prev/curr` is the critical spot.

**Comment by mackworth** [comment] 2016-10-13 16:17
Oh, even stranger. If I redirect stdIn to the file  (`<$f`), it works fine; but if I pipe it in from cat (`cat $f |'), it fails.  I was unaware these could be different.  My only guess so far is there's an uninitialized something somewhere, and putting it in a pipe causes it to initialized differently?

**Comment by cfsmp3** [comment] 2016-10-13 18:22
I ran it with valgrind and it didn't report any incorrect use of memory.

I can't reproduce no matter what I try, but I'm using linux, not Mac... so
it's not the same thing.

**Comment by TheRealUnknownDeveloper** [comment] 2017-01-08 19:37
INVALID: Sample missing
Cannot Reproduce

**Comment by MatejMecka** [comment] 2017-01-08 19:40
Invalid! Sample missing. Cannot Reproduce

**Comment by cfsmp3** [comment] 2017-01-08 19:55
@mackworth can you make that file (or another one with the same problem) available for download? We want to take another look.

**Comment by mackworth** [comment] 2017-01-08 20:49
I have restored that file to my dropbox again.  

https://dl.dropboxusercontent.com/u/21507587/RobotChicken-RandomFailuresBI.mpg

**Comment by MatejMecka** [comment] 2017-01-08 23:05
The Download failed multiple times for me. Can you post it on a different site.

**Comment by mackworth** [comment] 2017-01-08 23:16
Hmm, maybe cause it's treating it as a video file.  I renamed it to .jnk; please try it again.

If not, I'm not currently subscribed to any filesharing site that shares by URL, just by email-based distribution, can you suggest one?

**Comment by mackworth** [comment] 2017-01-08 23:17
so revised URL is https://dl.dropboxusercontent.com/u/21507587/RobotChicken-RandomFailuresBI.jnk

**Comment by mackworth** [comment] 2017-01-09 05:07
Did that work?

**Comment by cfsmp3** [comment] 2017-01-09 05:09
@mackworth it did for me - don't know about @MatejMecka who is going to look into it. But anyway it's not a dropbox problem for sure.

**Comment by MatejMecka** [comment] 2017-01-09 09:48
@mackworth it did this time!

**Comment by MatejMecka** [comment] 2017-01-09 09:57
I'm not seeing any problems at all: ```
Opening file: /Users/matejmecka/Downloads/RobotChicken-RandomFailuresBI.jnk
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Creating /Users/matejmecka/Downloads/RobotChicken-RandomFailuresBI.srt

Found large gap(466712) in PTS! Trying to recover ...
  0%  |  00:00
Found large gap(466713) in PTS! Trying to recover ...

Found large gap(466720) in PTS! Trying to recover ...

Found large gap(466721) in PTS! Trying to recover ...

Found large gap(466716) in PTS! Trying to recover ...

Found large gap(466717) in PTS! Trying to recover ...

Found large gap(466714) in PTS! Trying to recover ...

Found large gap(466715) in PTS! Trying to recover ...

Found large gap(466718) in PTS! Trying to recover ...

Found large gap(466719) in PTS! Trying to recover ...
XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: TV-MA (Mature Audience Only)
XDS: 
  XDS Notice: Network is now CARTOON   
XDS Notice: Program is now Robot Chicken, Easter Basket
XDS: CGMS: One generation of copies can be made
XDS: APS: No APS
XDS: Redistribution Control Descriptor: 0
XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: TV-14 (Parents Strongly Cautioned)
XDS: [Violence] [Sexual Situations] [Adult Language] [Sexually Suggestive Dialog] 
XDS Notice: Program is now   
XDS Notice: Program is now Robot Chicken, Celebrity Rocket
100%  |  15:02
Number of NAL_type_7: 801
Number of VCL_HRD: 0
Number of NAL HRD: 41
Number of jump-in-frames: 779
Number of num_unexpected_sei_length: 0

Total frames time:	  00:30:04:202  (54072 frames at 29.97fps)

Min PTS:				02:09:46:309
Max PTS:				02:24:48:559
Length:				 00:15:02:250
Done, processing time = 7 seconds
This is beta software. Report issues to carlos at ccextractor org...
```
Tested on Mac Os X El Capitan on a Macbook Air 2011(11-inch, Mid 2011).  
Also the subtitles look ok. Used the second URL you gave me with the .jnk

**Comment by MatejMecka** [comment] 2017-01-09 11:02
Which Version are you using? I used the latest one from GitHub

**Comment by mackworth** [comment] 2017-01-09 16:24
I just ran it again, and got almost identical results to before: it worked the first time, failed the second. Overall worked 5 times out of 20. I've included a bad run's logs as well as  a good one. 

The version I'm using is compiled a couple days ago from the github release, using the build.command. I've put my binary copy at https://dl.dropboxusercontent.com/u/21507587/ccextractor

I note your log is identical to mine except yours says "100%  |  15:02" versus my "Streaming | 15:00". Are you piping  `cat $filename`  into ccextractor?  If not, as I discussed above, if you're even do a stdin redirect, it doesn't trigger this problem.
````
ccextractor=./ccextractor
f=~/Dropbox/Public/RobotChicken-RandomFailuresBI.jnk
for i in $(seq 1 1 20); do
cat "$f" | $ccextractor -bi - -o junk3.srt > "junkNew$i.log"
if [ $? -eq 0 ]
then
  echo "OK   - $f"
else
  echo "Fail - $f"
fi
done
````
Here's my output:
````
CCExtractor 0.84, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: stdin
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: Yes, no timeout] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Reading from standard input
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Creating junk3.srt

Found large gap(466712) in PTS! Trying to recover ...
Streaming |  00:00
Found large gap(466713) in PTS! Trying to recover ...

Found large gap(466720) in PTS! Trying to recover ...

Found large gap(466721) in PTS! Trying to recover ...

Found large gap(466716) in PTS! Trying to recover ...

Found large gap(466717) in PTS! Trying to recover ...

Found large gap(466714) in PTS! Trying to recover ...

Found large gap(466715) in PTS! Trying to recover ...

Found large gap(466718) in PTS! Trying to recover ...

Found large gap(466719) in PTS! Trying to recover ...
XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: TV-MA (Mature Audience Only)
XDS: 
  XDS Notice: Network is now CARTOON   
XDS Notice: Program is now Robot Chicken, Easter Basket
TS continuity counter not incremented prev/curr 4/9
````
Here's a successful run (almost identical to yours, except as noted above)...
````
CCExtractor 0.84, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: stdin
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: Yes, no timeout] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Reading from standard input
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Creating junk3.srt

Found large gap(466712) in PTS! Trying to recover ...
Streaming |  00:00
Found large gap(466713) in PTS! Trying to recover ...

Found large gap(466720) in PTS! Trying to recover ...

Found large gap(466721) in PTS! Trying to recover ...

Found large gap(466716) in PTS! Trying to recover ...

Found large gap(466717) in PTS! Trying to recover ...

Found large gap(466714) in PTS! Trying to recover ...

Found large gap(466715) in PTS! Trying to recover ...

Found large gap(466718) in PTS! Trying to recover ...

Found large gap(466719) in PTS! Trying to recover ...
XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: TV-MA (Mature Audience Only)
XDS: 
  XDS Notice: Network is now CARTOON   
XDS Notice: Program is now Robot Chicken, Easter Basket
XDS: CGMS: One generation of copies can be made
XDS: APS: No APS
XDS: Redistribution Control Descriptor: 0
XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: TV-14 (Parents Strongly Cautioned)
XDS: [Violence] [Sexual Situations] [Adult Language] [Sexually Suggestive Dialog] 
XDS Notice: Program is now   
XDS Notice: Program is now Robot Chicken, Celebrity Rocket
Streaming |  15:00
Number of NAL_type_7: 801
Number of VCL_HRD: 0
Number of NAL HRD: 41
Number of jump-in-frames: 779
Number of num_unexpected_sei_length: 0

Total frames time:	  00:30:04:202  (54072 frames at 29.97fps)

Min PTS:				02:09:46:309
Max PTS:				02:24:48:559
Length:				 00:15:02:250
Done, processing time = 2 seconds
This is beta software. Report issues to carlos at ccextractor org...
````

**Comment by mackworth** [comment] 2017-01-13 21:01
Were you able to recreate?

**Comment by cfsmp3** [comment] 2017-01-20 00:58
GSoC qualification: This issues gives 2 points.

**Comment by cfsmp3** [comment] 2017-11-20 19:27
Sample link dead. Closing - reopen if the issue is still present (but with a permanent link).

**Comment by mackworth** [comment] 2017-11-20 19:50
Sorry, hadn't heard anything in so long, I cleaned up my dropbox directory to save space.  Does @MatejMecka still have a copy?

**Comment by mackworth** [comment] 2018-01-24 18:30
aha! Found it on a backup:

https://www.dropbox.com/s/zo6ta9d8ppl093p/RobotChicken-RandomFailuresBI.mpg?dl=0

 @cfsmp3: It appears I don't have the ability to reopen a closed issue.

**Comment by cfsmp3** [comment] 2018-10-15 21:40
Closing this - not sure if it's active or if the original report is still accurate (maybe something was fixed).
@mackworth if this is still causing you problems could you open a new ticket with current details? We'll add it a a GCI task.

**Closed by cfsmp3** 2018-10-15 21:40 UTC
