### ISSUE TITLE
[BUG] 608/708 captions not being converted to webvtt

### ISSUE THREAD

**Issue by shaunflagg** [CCExtractor/ccextractor#1410] opened 2022-01-24 21:27 UTC
CCExtractor version: 0.94

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? YES
- What platform did you use?  Linux and Mac
- What were the used arguments? `ccextractor file.mp4 -out-webvtt`

# Video links

N/A

# Additional information

I have some video files with 608/708 embedded captions and have been using ccxtractor to generate webvtt captions files. This has been successful with version 0.88 for some time. I recently installed version 0.94 and get this error 

```
[CEA-708] dtvcc_handle_G0: Window has to be defined first
[CEA-708] dtvcc_handle_CWx_SetCurrentWindow: window [0] is not defined
Segmentation fault
```

**Comment by PunitLodha** [comment] 2022-01-25 09:56
Please share the videos for which you get this error.

**Comment by shaunflagg** [comment] 2022-02-08 04:02
@PunitLodha you can see the mp4 and vtt files here https://drive.google.com/drive/folders/12GflmtA6M6aTIH1VEQ4TVOYVO05CpMd6?usp=sharing

**Comment by PunitLodha** [comment] 2022-02-09 06:25
I am able to extract correct vtt captions for this file on 0.94. Could you please share the output of `ccextractor --version` and also tell where have you installed ccextractor from?

**Comment by cfsmp3** [comment] 2023-03-22 04:48
Closing because I can't reproduce. I did fix an unrelated issue (small memory leak) with this sample though.

@shaunflagg feel free to reopen if you can reproduce with current master.

**Closed by cfsmp3** 2023-03-22 04:48 UTC
