### ISSUE TITLE
CCextractor behaves unexpectedly when processing both CEA-608 fields.

### ISSUE THREAD

**Issue by OmegaVVeapon** [CCExtractor/ccextractor#687] opened 2017-02-15 15:49 UTC
For CEA-608 extraction, the `help`states that:
```
Options that affect what will be processed:
          -1, -2, -12: Output Field 1 data, Field 2 data, or both
                       (DEFAULT is -1)
```
The `-1` and `-2` options both create a `<media_name>.srt` file with the correct CEA-608 CC's according to the specified field. However, specifying both fields (`-12`), will create `<media_name>_1.srt` and `<media_name>_2.srt` files. However, the first file will contain interleaved CCs from both fields inside of it, leaving the second file empty. For example, this is what occurs when trying to extract both the english and french CEA-608 CCs from a media:

_media_1.srt_

```
00:00:36,746 --> 00:00:40,205
 <i> [boy]</i>
 <i> If you must blink, do it now.</i>

4
00:00:36,704 --> 00:00:40,581
  (garçon):<i> Si tu dois cligner</i>
<i>des yeux, fais-le tout de suite.</i>
```

_media_2.srt_
```

```

**Comment by Izaron** [comment] 2017-02-15 16:03
Can you please attach your video file here? For example, as link to Dropbox file.

**Comment by OmegaVVeapon** [comment] 2017-02-15 21:42
I'm afraid I can't share the media that repro'd the issue (NDA), and I don't seem to have any other medias with 2 CEA-608 fields. If I do find something to share, what address should I send the Dropbox link to?

**Comment by cfsmp3** [comment] 2017-02-15 23:35
Just write it here in a comment.

Basically you have two options

1) Work with us publicly, meaning samples and code are available for
everyone to use as needed.
2) Work with us privately. Privately always means under contract. You can
hire me or anyone else in the team you like. I'll be happy to sign a NDA if
needed.

What is not going to happen is that we work on anything private without
payment :-)

**Comment by cfsmp3** [comment] 2018-01-11 22:36
Closing since user didn't reply to last post and we don't have a sample.

**Closed by cfsmp3** 2018-01-11 22:36 UTC

**Comment by harrynull** [comment] 2018-01-12 00:46
Is this a common issue that can be reproduced in all medias with 2 CEA-608 fields?
