### ISSUE TITLE
[PROPOSAL] fresh GUI installation says 'url_launcher_windows_plugin.dll needed'

### ISSUE THREAD

**Issue by anemochore** [CCExtractor/ccextractor#1369] opened 2021-08-05 13:48 UTC
I downloaded and installed v0.91 installer and it won't even launch. Please check and include your dependencies before release. :(

**Comment by canihavesomecoffee** [comment] 2021-08-05 17:55
Duplicate of #1367.

See a temporary workaround until 0.92 is released.

**Closed by canihavesomecoffee** 2021-08-05 17:55 UTC

**Comment by Techno-Disaster** [comment] 2021-08-05 20:56
@anemochore were you able to install the GUI? Do let me know if there's any further issue or you need help with anything else :D

Any suggestions/feat requests are also welcome :D
