### ISSUE TITLE
Cannot extract DVB subtitles from the TVEHD channel

### ISSUE THREAD

**Issue by ruralman** [CCExtractor/ccextractor#279] opened 2016-02-10 09:46 UTC
hola a todos,
A pesar que el mediainfo dice:
Video:
PID: 0x12D(H.264)
Audio:
PID: 0x12E(spa)[PD]
PID: 0x12F(qaa)[PD]
PID: 0x130(spa)[PD]
Teletexto:
Vacío
Subtítulos DVB:
PID: 0x131(spa_0x14_p1_a2 ) 

No consigo extraerlos con el ccextractor(con subtitle edit ,logro visualizarlos)
adjunto archivos de ejemplo:
https://drive.google.com/file/d/0B_gQLghxiDPxakJOUkNLSkl2Z1U/view?usp=drive_web
https://drive.google.com/file/d/0B_gQLghxiDPxTDRseU5SMUpKVVk/view?usp=drive_web

**Comment by anshul1912** [comment] 2016-02-14 11:09
are you able to see subtitles with any other video player

**Comment by ruralman** [comment] 2016-02-29 10:13
si,los subtitulos se ven (mplayer),pero no se pueden extraer.

2016-02-14 12:09 GMT+01:00 Anshul Maheshwari <notifications@github.com>:

**Comment by vinayakathavale** [comment] 2016-03-18 04:07
@ruralman you need to use -out=spupng  as one of the arguments
 
refer [link](http://ccextractor.com/spupng.html) for details.

**Comment by cfsmp3** [comment] 2016-07-05 19:35
This file: 000prueba brujula.ts
Causes a crash which is definitely related to the OCR (with no tesseract the spupng files are generated just fine, even though of course we don't have the text in the XML file). 
With tesseract there's a quick crash. VS doesn't say where though, so I assume it's inside one of the libraries.
If exporting to .srt the generated file before the crash contains garbage:

1
00:00:00,001 --> 00:00:00,000
I-Ian: rnllnhnc Ilniunr-can
I I“, IIIIpI\lII\I§ IpIIIIVGI§\I§
r'7-""*1-~1

Assigning to Anshul (sorry) as it's DVB-OCR related.

**Comment by Abhinav95** [comment] 2016-08-10 14:07
The problem with these two files is that the image which we are doing OCR on is not created properly. I'm taking a deeper look into it.

**Comment by cfsmp3** [comment] 2016-11-07 20:47
@ruralman do you still have this problem with the current version?

**Comment by Izaron** [comment] 2017-01-02 11:40
I researched this issue.
Firstly, we have subtitles, but the display time starts from 1590 minutes. Something is broken at this point anyway.
Secondly, we get errors because 'start_y' or 'end_y' was uninitialized. I initialized them to 0.

![image](https://cloud.githubusercontent.com/assets/5406399/21588433/a9815164-d0f7-11e6-9475-97472041daa3.png)

Anyway was other bugs:

![image](https://cloud.githubusercontent.com/assets/5406399/21588452/e4315458-d0f7-11e6-957e-33739eb6768a.png)

After patching, I received such output:

![image](https://cloud.githubusercontent.com/assets/5406399/21588557/f8ff26a2-d0f8-11e6-8432-af45e112b6ff.png)

And .srt file - [hercules.srt](https://gist.github.com/Izaron/aeba650fbfab1ef89e20b3765886c712) What have start time 26:30:43. 

I would venture to suggest that the error in the .ts file recording.

**Comment by cfsmp3** [comment] 2017-01-20 00:55
prueba_hercules.ts crashes with current version.
prueba_brujula.ts doesn't crash but output is garbage.

GSoC qualification: This issues gives 3 points.

**Comment by ruralman** [comment] 2017-01-23 20:18
thanks for your answer

2017-01-20 1:55 GMT+01:00 Carlos Fernandez Sanz <notifications@github.com>:

**Comment by canihavesomecoffee** [comment] 2017-11-18 16:01
@ruralman I modified your title to English so that it's a bit clearer :)

Hope you don't mind.

**Comment by harrynull** [comment] 2017-12-26 10:21
`000prueba hercules.ts` works perfectly. Subtitles are extracted correctly.
`000prueba brujula.ts`'s output is quite messed up. The cause is that the subtitle is divided into multiple regions, like shown below:
![test 4](https://user-images.githubusercontent.com/7413706/34354301-3f848caa-ea68-11e7-9913-1fbaa8a70985.png)
![test 3](https://user-images.githubusercontent.com/7413706/34354300-3f52c38c-ea68-11e7-9139-ebc0a6388837.png)
![test 2](https://user-images.githubusercontent.com/7413706/34354298-3f1f9458-ea68-11e7-9ad7-cf221a33cf9d.png)
![test](https://user-images.githubusercontent.com/7413706/34354297-3eec1006-ea68-11e7-9396-9f021e4268dc.png)
The reason `-spupng` working fine is that it merges the regions before saving to file.

My suggestion is that we should merge the regions before passing to OCR.
Possible flaw: The positioning of the subtitle could be hard.
Possible solution: Only merge the subtitles that are nearby.

**Comment by cfsmp3** [comment] 2017-12-26 13:46
This is quite interesting.
If spupng works well then it's clearly a solvable problem.
Do you want to give it a go?

**Comment by harrynull** [comment] 2017-12-26 14:25
@cfsmp3 It doesn't seem to be easy to fix, but I will give it a try.

**Closed** 2017-12-28 08:19 UTC
