### ISSUE TITLE
[BUG] CCExtractorGUI 8.5 does not work on a video file with MPEG-TS container 

### ISSUE THREAD

**Issue by edr1** [CCExtractor/ccextractor#752] opened 2017-07-13 23:28 UTC
Hello there,
Please, I have a video file with MPEG-TS format (Transport Stream) and 2 text streams with closed caption data embedded into the file (EIA 608 / EIA 708), but unfortunately the CCExtractorGUI is not able to extract the closed caption data because the program seems to stuck in 0% with a message: 
**"Found large gap(4874420) in PTS! Trying to recover ..."**
The command line with all parameters set in the GUI is as follow:
**C:\Program Files (x86)\CCExtractor\ccextractorwin.exe  --gui_mode_reports  -in=ts -autoprogram  -out=txt -bom -utf8 [+input files]**

[testTS_subtitles_RTMP_2.zip](https://github.com/CCExtractor/ccextractor/files/1146933/testTS_subtitles_RTMP_2.zip)

The activity messages are:

--------------------------------------------------------------------------
Input: E:\IMEX\POC\TVGLOBO\NEWMEDIA_STREAM_MEDIAELEMENT\TEST_ELEMENTAL_2103\testTS_subtitles_RTMP_1.ts
[Extract: 1] [Stream mode: Transport]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: Yes]
[Target format: .txt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

Opening file: E:\IMEX\POC\TVGLOBO\NEWMEDIA_STREAM_MEDIAELEMENT\TEST_ELEMENTAL_2103\testTS_subtitles_RTMP_1.ts

Analyzing data in general mode
Creating E:\IMEX\POC\TVGLOBO\NEWMEDIA_STREAM_MEDIAELEMENT\TEST_ELEMENTAL_2103\testTS_subtitles_RTMP_1.txt

Found large gap(4874420) in PTS! Trying to recover ...

-----------------------------------------------------------------

Please find attached the video file with MPEG-TS format to take a look at your side and screen shoots with media information and VLC showing the subtitle tracks with closed caption 1:
![mediainfo](https://user-images.githubusercontent.com/1331136/28191944-a66cbd34-6809-11e7-8a24-107cdbd24b02.png)
![vlc_subtitle_subtrack_closedcations_1_data](https://user-images.githubusercontent.com/1331136/28191949-a99d109e-6809-11e7-9edb-6fe8768da4b0.png)

. Could you give some directions in order to find out the issue?

Thank you very much
Erick Delgado

**Comment by cfsmp3** [comment] 2017-12-05 23:59
Can't reproduce, seems fixed in current master. Please reopen the issue if needed.

**Closed by cfsmp3** 2017-12-05 23:59 UTC

**Comment by TeeJiiAl** [comment] 2018-06-11 07:10
I have this same issue with large gaps in certain files. Unfortunately I cannot give samples, but here is the output.
Tried versions: 0.85 (windows 10) and 0.86 (ubuntu).

Is there any fix on this? It does indeed work in some of the files, although there is similar timestamp issues.

CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ****.ts
[Extract: 1] [Stream mode: Transport]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .xml] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]


-----------------------------------------------------------------

Opening file: ****\****_-_****.ts

Analyzing data in general mode
Creating****\****_-_****.xml
Changed fps using NAL to: 25.000000

Found large gap(2691754) in PTS! Trying to recover ...

Found large gap(2691762) in PTS! Trying to recover ...

Found large gap(2691758) in PTS! Trying to recover ...

Found large gap(2691756) in PTS! Trying to recover ...

Found large gap(2691760) in PTS! Trying to recover ...
