### ISSUE TITLE
File that makes CCExtractor crash

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#281] opened 2016-02-20 10:42 UTC
[1455449602_727724800_2.zip](https://github.com/CCExtractor/ccextractor/files/139080/1455449602_727724800_2.zip)
The attached file caused a really early crash.

**Comment by vinayakathavale** [comment] 2016-03-07 23:06
File did not cause a crash for me 
[output](http://pastebin.com/kj0vG2kB) on stdout 
[contents](http://pastebin.com/L33Sctqx) of the .srt file created

**Comment by Arbitrer** [comment] 2016-03-07 23:34
@vinayakathavale what Operating system , IDE do you use?

**Comment by vinayakathavale** [comment] 2016-03-08 00:05
OS: ubuntu 14.04 
Oh my bad Got the former output on installing  v0.79
I am getting a segmentation fault after installing the latest build

**Comment by phanindra707** [comment] 2016-03-09 04:49
CCextractor didnot crash in mine.It produced the subtitles
![stdout](https://cloud.githubusercontent.com/assets/9819126/13625679/1cb882be-e5e0-11e5-90f4-3d35b1e04de2.png) output for subtitles

But the problem is after compiling the ts file it is not playing in vlc before it played the video and subtitles are being generated for each and every compilation.

**Comment by vinayakathavale** [comment] 2016-03-09 07:05
@phanindra707  the issue has been fixed by the following commit https://github.com/CCExtractor/ccextractor/commit/877ee7b2c7b4d2c660417f792257ed545839607f

**Comment by canihavesomecoffee** [comment] 2016-03-09 07:07
@vinayakathavale Could you use the "Closes #281" in the PR next time? Then this issue will be closed automatically :)

**Comment by vinayakathavale** [comment] 2016-03-09 13:31
I didn't make the commit but will keep that in mind thanks :+1:

**Comment by canihavesomecoffee** [comment] 2016-05-22 11:43
Can be closed once #323 is merged. Tested the PR manually and it solves this issue.

**Closed** 2016-05-22 16:38 UTC
