### ISSUE TITLE
[BUG] Error: Syntax problem: Final 0xFF marker missing.

### ISSUE THREAD

**Issue by bubbaprog** [CCExtractor/ccextractor#1001] opened 2018-09-11 15:22 UTC
CCExtractor version 0.87

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.
- [X] I absolutely love CCExtractor, but have not contributed previously.

- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [ ] Linux - [X] Mac
- What were the used arguments? --out=bin

SAMPLE VIDEO: 
https://drive.google.com/file/d/1loifBNC-vEACBt16896tGi5OtFaVJA9l/view?usp=sharing

**Additional information**

Subtitles confirmed to work in playback in VLC, but ccextractor returns Syntax problem when attempting to extract.

**Comment by sudz123** [comment] 2018-09-29 09:01
Hi I am new to ccextractor, but I'd like to understand it better. I'd like to help solve this issue, is it up for grabs? How can I go about it? I am working on an OSX machine.

**Comment by cfsmp3** [comment] 2018-09-29 16:48
Yes, go for it!

**Comment by MatejMecka** [comment] 2018-10-29 17:17
I Commented out the line causing the error and the output is terrible.

The subtitle begins 10 seconds later and i miss a lot of subtitled commentary.  Even with the 10 second delay the subtitles are never matched with the Commentators.

Also for some reason the last line in the subtitle block is repeated on the next beginning block.

You can also notice that the last part is cutout.

I've attached the .srt file below and I'll continue debugging to find the cause.

```
1
00:00:10,843 --> 00:00:13,912
>> WE KICKOFF A BUSY DAY ON CBS 
SPORTS NETWORK.                 

2
00:00:13,914 --> 00:00:15,581
SPORTS NETWORK.                 
ALONG THE BANKS OF THE HUDSON   

3
00:00:15,583 --> 00:00:16,615
ALONG THE BANKS OF THE HUDSON   
RIVER AT THE UNITED STATES      

4
00:00:16,617 --> 00:00:18,283
RIVER AT THE UNITED STATES      
MILITARY ACADEMY, THE CADETS    

5
00:00:18,285 --> 00:00:21,019
MILITARY ACADEMY, THE CADETS    
HAVE MARCHED IN, ALL4,400       

6
00:00:21,021 --> 00:00:23,988
HAVE MARCHED IN, ALL4,400       
STRONG READY FOR ARMY'S HOME    

7
00:00:23,990 --> 00:00:24,356
STRONG READY FOR ARMY'S HOME    
OPENER.                         

8
00:00:24,358 --> 00:00:25,490
OPENER.                         
HERE ARE THE BLACK KNIGHTS ON   

9
00:00:25,492 --> 00:00:27,225
HERE ARE THE BLACK KNIGHTS ON   
THE PLAYING SURFACE HERE FOR THE

10
00:00:27,227 --> 00:00:30,328
THE PLAYING SURFACE HERE FOR THE
FIRST TIME IN 2018.             

11
00:00:30,330 --> 00:00:33,098
FIRST TIME IN 2018.             
THEY WELCOME IN ANOTHER FCS     

12
00:00:33,100 --> 00:00:35,000
THEY WELCOME IN ANOTHER FCS     
INDEPENDENT LIKE THEMSELVES, THE

13
00:00:35,002 --> 00:00:37,436
INDEPENDENT LIKE THEMSELVES, THE
1-0 FLAMES OF LIBERTY           

14
00:00:37,438 --> 00:00:37,836
1-0 FLAMES OF LIBERTY           
UNIVERSITY.                     

15
00:00:37,838 --> 00:00:39,370
UNIVERSITY.                     
GREAT TO SEE YOU.               

16
00:00:39,372 --> 00:00:40,906
GREAT TO SEE YOU.               
WELCOME UPSIRS TO OUR OFFICE    

17
00:00:40,908 --> 00:00:44,109
WELCOME UPSIRS TO OUR OFFICE    
OF PLEASURE AND AN HONOR TO BE  

18
00:00:44,111 --> 00:00:47,645
OF PLEASURE AND AN HONOR TO BE  
WITH YOU, ALONGSIDE MY BROADCAST

19
00:00:47,647 --> 00:00:48,413
WITH YOU, ALONGSIDE MY BROADCAST
PARTNER.                        

20
00:00:48,415 --> 00:00:50,949
PARTNER.                        
WITH JAY FEELY, I'M BEN HOLDEN. 

21
00:00:50,951 --> 00:00:54,286
WITH JAY FEELY, I'M BEN HOLDEN. 
JAY, LAST YEAR A RECORD-SETTING 

22
00:00:54,288 --> 00:00:56,354
JAY, LAST YEAR A RECORD-SETTING 
SEASON FOR JEFF MONKEN.         

23
00:00:56,356 --> 00:00:57,122
SEASON FOR JEFF MONKEN.         
TEN WINS.                       

24
00:00:57,124 --> 00:00:58,423
TEN WINS.                       
THEY BEAT NAVY.                 

25
00:00:58,425 --> 00:00:59,791
THEY BEAT NAVY.                 
THEY WON A BOWL GAME.           

26
00:00:59,793 --> 00:01:00,025
THEY WON A BOWL GAME.           
TH                              
```

**Comment by cfsmp3** [comment] 2018-11-02 00:08
Fixed in master

**Closed by cfsmp3** 2018-11-02 00:08 UTC
Labels: GCI18
