### ISSUE TITLE
CEA-608 Export to RAW/BIN Fails

### ISSUE THREAD

**Issue by bwhansen** [CCExtractor/ccextractor#102] opened 2014-08-24 10:58 UTC
Hey, think I found a bug...

My input files are m4v with CEA-608 stream (iTunes).  If I output to SRT it works fine.  But attempting to output to RAW / DVDRAW / BIN doesn’t work (output files are empty.)

Command line:
C:\Program Files (x86)\CCExtractor\ccextractorwin.exe  --gui_mode_reports  -in=mp4 -autoprogram  -out=raw -o "C:\somefolder\s01e01_ccextract.raw" -latin1 --nofontcolor --notypesetting -noteletext [+input files]

The only option I’m changing (other than the output file name) is the –out argument.  CCExtractor GUI "Preview" text area displays all captions as per normal every time, but unless output is set to SRT the files are empty.

CCExtractor 0.73 (also tested with CCExtractor 0.69)
Windows 8.1 Pro 64-Bit with UAC enabled; NTFS file system; Visual C++ 2013 Runtime installed.

Happy to answer any question, but go easy on me - I'm a CC n00b.

**Comment by theAprel** [comment] 2015-02-13 23:18
This issue is still active. I have a wtv file with eia 608 CC. It extracts to srt format properly, but throws a SegFault if set to bin output:

    File seems to be a WTV, enabling WTV mode
    Analyzing data in general mode
      0%  |  00:00Segmentation fault

raw doesn't work, either. It doesn't produce SegFault; rather, reads whole file and indicates success but output file is only 4 bytes long.

**Comment by cfsmp3** [comment] 2015-02-14 10:18
OK, I'll look into it asap so it's fixed in 0.76.

Can you submit a sample that causes the crash?

**Comment by mailumangjain** [comment] 2015-02-14 10:21
cfsmp3, I want to take up this bug if possible.
@theAprel provide us with the sample.

**Comment by theAprel** [comment] 2015-02-14 22:42
@mailumangjain I have reached out to you in an email with a sample.

**Comment by cfsmp3** [comment] 2015-04-08 14:57
Tested with in iTunes file, seems fixed.

**Comment by mailumangjain** [comment] 2015-04-18 08:43
The sample used in this issue (.wtv) format has repeated CC in output(.srt). I am facing this in most of .wtv format files.

**Comment by theAprel** [comment] 2015-04-20 01:16
@mailumangjain I'm not sure if this is a bug. I think it's meant to mimic as closely as possible the CC you would see on TV. On TV, CC often scroll with the dialogue, whereas the srt format is static and must be redrawn to the screen at each specified timecode.

I think there is also a command-line flag that will limit repetition when creating srt files.

**Comment by mailumangjain** [comment] 2015-04-20 04:14
okay @theAprel. I get it.

**Comment by windyboy1704** [comment] 2019-07-26 07:06
This issue still happens on 0.88, other formats work normally. I also tried using SCC_RIP and it gives `no caption found` when the caption stream is CEA-608.
[Sample iTunes preview video](https://github.com/CCExtractor/ccextractor/files/3434596/mzvf_1402545844578339563.640x480.h264lc.U.p.zip)

**Comment by P1YU5H-50N1** [comment] 2020-08-18 17:41
Can I take this up?

**Comment by cfsmp3** [comment] 2020-08-18 22:04
Sure

**Comment by P1YU5H-50N1** [comment] 2020-08-20 10:22
I am on it! Should I start somewhere in particular?

**Comment by cfsmp3** [comment] 2020-08-20 21:06
Start by reproducing the problem :-)

**Comment by 85ayush** [comment] 2021-02-23 11:05
I would like to work on this issue, I am a beginner to open source contribution. Can you please guide me?

**Comment by cfsmp3** [comment] 2021-11-21 18:19
Closing due to no sample being available.

**Closed by cfsmp3** 2021-11-21 18:19 UTC
Labels: good-first-task, needs-confirmation-of-being-broken, difficulty: easy

**Comment by canihavesomecoffee** [comment] 2021-11-21 18:24
@anshul1912 Do you still happen to have the original sample the original author sent you?
