### ISSUE TITLE
.79 crashes on small .bin files

### ISSUE THREAD

**Issue by Kapstew** [CCExtractor/ccextractor#287] opened 2016-02-26 15:17 UTC
I've found what I believe to be bug in CCExtractorwin.exe version 0.79.   When I attempt to extract captioning from a file that’s from a 5-minute recording ccextractorwin crashes.  

Ccextractorwin version 0.77 does not crash when extracting text from this same file.  I’ve had no problems extracting text from a 30 to 60 minute recording with 0.79.

I’m using this command line:

ccextractorwin "C:\Source\WMTV_Today_6_955am.bin" -ttxt -o Output79.txt

I’ve attached the .bin (with .txt extension) file that I’ve been using to extract from and a text file from a successful output from version 0.77 that was run from this file.
[Output77.txt](https://github.com/CCExtractor/ccextractor/files/148412/Output77.txt)

[WMTV_Today_6_955am.bin.txt](https://github.com/CCExtractor/ccextractor/files/148410/WMTV_Today_6_955am.bin.txt)

**Comment by abhibansal530** [comment] 2016-03-08 15:30
This issue was due to fflush,which is fixed now. 
877ee7b2c7b4d2c660417f792257ed545839607f

**Comment by canihavesomecoffee** [comment] 2016-05-22 09:14
Can be closed once #323 is merged (after bot confirms that PR doesn't introduce new regressions). Tested the PR manually and it solves this issue.

**Closed** 2016-05-22 16:38 UTC
