### ISSUE TITLE
[BUG] Does not build with gcc-10 and -Werror

### ISSUE THREAD

**Issue by sdelafond** [CCExtractor/ccextractor#1260] opened 2020-04-24 10:16 UTC
CCExtractor version: 0.88

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? Linux

# Additional information

0.88 fails to build when using gcc-10 with -Werror (while it goes fine with gcc-9); most of the errors are redefinitions of `ccx_dtvcc_default_pen_color`, `ccx_dtvcc_default_pen_color`, and `signal_ctx`.

The full log can be found at https://people.debian.org/~doko/logs/gcc10-20200225/ccextractor_0.87+ds1-1_unstable_gcc10.log.

This bug was originally reported in Debian, at https://bugs.debian.org/957071.

**Comment by NilsIrl** [comment] 2020-04-27 08:58
This has been fixed on master

**Comment by NilsIrl** [comment] 2020-04-27 08:58
Duplicate of #1225

**Closed** 2020-04-28 16:53 UTC
Labels: difficulty: easy
