### ISSUE TITLE
[BUG] Burned-in extraction not working

### ISSUE THREAD

**Issue by madnesofjuice** [CCExtractor/ccextractor#1111] opened 2019-09-30 15:49 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : CCExtractor detailed version info
        Version: 0.88

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [ X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [ X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X ] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [X ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [x ] Windows - [ ] Linux - [ ] Mac
- What were the used arguments?

**Video links (replace text below with your links)**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

So, i tryied to extract burned-in subtitles with gui and with command line but im getting the same error:
Error: Error: Parameter -hardsubx not understood.
in cmd:
ccextractorwin.exe 1.mkv -hardsubx -subcolor white -min_sub_duration 0.3 -conf_thresh 60

**Comment by vikramcs** [comment] 2019-11-07 18:39
I changed a few settings from the default initially. then after this error, changed back to defaults on the "About & Save" TAB.

I'll be opening separate issue for the garbled text in MCEBuddy

Command line per GUI for modified settings:
C:\Program Files (x86)\CCExtractor\ccextractorwinfull.exe --gui_mode_reports -in=wtv -autoprogram -out=srt -bom -cf C:\Users\sj\Desktop\CCExtractor_Elementary_Stream.txt -goppts -latin1 --endcreditstext "Generated by CCExtractor\nhttp://www.ccextractor.org" --endcreditsforatleast 6 --endcreditsforatmost 3 -hardsubx -subcolor white -conf_thresh 60 [+input files]

**Comment by vr8hub** [comment] 2020-01-08 03:03
Is there any update on this? I just encountered this error as well with the `brew` version on Mac, and then re-compiled from source to make sure it wasn't a `brew` issue.

**Comment by canihavesomecoffee** [comment] 2020-01-08 08:01
Well, you'd have to make sure that you compiled the program to enable that feature, as (if I'm recalling it correctly), it's not enabled by default.

**Comment by vr8hub** [comment] 2020-01-08 14:38
Yes, thanks, I discovered that after a lot more time spelunking. The compile guide doesn't mention it at all, the build.command in the Mac directory doesn't mention it, so there's no obvious way for a newbie to know that. I tried using the autotools configure/make in the Mac directory and then took a look at the configure output to discover that it wasn't enabled by default. But enabling it causes undefined symbol errors, so I'll do some more investigation and open a new issue for that if I can't figure out the problem.

**Comment by gauravahlawat81** [comment] 2020-01-13 12:55
Hey,I have been getting the same error. Even though I ran the command
`make ENABLE_HARDSUBX=yes`
Still whenever I am giving it the `-hardsubx` argument, It says 

> Error: Error: Parameter -hardusbx not understood.

**Comment by gauravahlawat81** [comment] 2020-01-13 16:58
Okay now for me it's working. As I ran command
`make ENABLE_HARDSUBX=yes` a file name 

> build_hardsubx
was created under linux directory and after that I ran the command 
`./build_hardsubx` . And after that I was able to use hardsubx as an arguement. All these things were done in `linux` directory and I am now able to use hardsubx with no issue at all.

**Comment by cfsmp3** [comment] 2020-01-25 23:19
Closing since sounds fixed - but @vr8hub feel free to reopen if you are still having problems

**Closed by cfsmp3** 2020-01-25 23:19 UTC

**Comment by denizdogan** [comment] 2021-03-11 20:07
This should be reopened. The issue is still as described in the original message and the workaround is not a solution.
